#!/bin/bash

if [ "$WORKSPACE" = "" ]; then
  echo 'WORKSPACE not set'
  exit 2
fi

export MODE="`cat ~/.citype`"
if [ "$MODE" = "" ]; then
  echo MODE must be set to 'test' or 'perf'
  exit 2
fi

cd /var/www
(ls -t logs-*.tar* | head -n 30; ls -t logs-*.tar*) | sort | uniq -u | xargs -r rm
(ls -t make-*.log | head -n 3; ls -t make-*.log) | sort | uniq -u | xargs -r rm
export TS="`date +%d.%m.%Y-%H.%M`"
if [ "`cat ~/.cistore`" = "memdb" ]; then export STORAGE="plasma"; else export STORAGE="memdb"; fi
if [ $((RANDOM%3)) -eq 0 ]; then export STORAGE="fdb"; fi
echo "$STORAGE" > ~/.cistore
echo '<html><head></head><body><pre>' > /var/www/gsi-current.html
chmod a+rx /var/www/gsi-current.html
dobuild clean 1>>/var/www/gsi-current.html 2>&1; rc=$?
test $rc -eq 0 && dotest 1>>/var/www/gsi-current.html 2>&1; rc=$?
echo '</pre>' >> /var/www/gsi-current.html
if [ $rc -eq 0 ]; then status=pass; else status=fail; fi
if [ "$MODE" = "perf" ]; then status=perf; fi
echo '<pre>' >> /var/www/gsi-current.html
gzip ${WORKSPACE}/logs.tar 2>&1 1>/dev/null
echo "Version: <a href='versions-$TS.cfg'>versions-$TS.cfg</a>" >> /var/www/gsi-current.html
echo "Build Log: <a href='make-$TS.log'>make-$TS.log</a>" >> /var/www/gsi-current.html
echo "Server Log: <a href='logs-$TS.tar.gz'>logs-$TS.tar.gz</a>" >> /var/www/gsi-current.html
echo "</pre><h1>Finished</h1></body></html>" >> /var/www/gsi-current.html
cp  /var/www/gsi-current.html /var/www/gsi-$STORAGE-$TS.$status.html
mv ${WORKSPACE}/make.log /var/www/make-$TS.log
mv ${WORKSPACE}/logs.tar.gz /var/www/logs-$TS.tar.gz
mv ${WORKSPACE}/versions.cfg /var/www/versions-$TS.cfg
if [ "$MODE" = "perf" ]; then dotiming; fi
dowatch

