#!/bin/bash

if [ ! -f ~/.cienv ]; then
cat > ~/.cienv <<EOF
    export CINAME=ci2i-unstable
    export CIBOT=true
    export WORKSPACE=/opt/build
    export RELEASE=6.5.0
    export MANIFEST="couchbase-server/mad-hatter/6.5.0.xml"
    export MODE="sanity,unit,functional,integration"
    export BRANCH="unstable"
    export MODE="test"
    export WATCHERS="siri@couchbase.com"
    export STORAGE="plasma"
    export PEGGED=0
    # use below if gerrit patchsets need to be ordered (so adding CI bot is not enough)
    # export GERRIT="10051 20012 31241"
EOF
fi
source ~/.cienv

if [ "$WORKSPACE" = "" ]; then
  echo 'WORKSPACE not set'
  exit 2
fi

if [ "$MODE" = "" ]; then
  echo MODE must be some combination of: 'lint,sanity,unit,functional,integration'
  exit 2
fi

if [ "$MANIFEST" == "" ]; then
  echo MANIFEST must be set
fi

if [ "$RELEASE" == "" ]; then
  echo RELEASE must be set
fi

if [ "$STORAGE" = "" ]; then
  export STORAGE="plasma"
fi

cd /var/www
(ls -t logs-*.tar* | head -n 30; ls -t logs-*.tar*) | sort | uniq -u | xargs -r rm
(ls -t make-*.log | head -n 3; ls -t make-*.log) | sort | uniq -u | xargs -r rm
export TS="`date +%d.%m.%Y-%H.%M`"
echo '<html><head></head><body><pre>' > /var/www/gsi-current.html
chmod a+rx /var/www/gsi-current.html
dobuild clean 1>>/var/www/gsi-current.html 2>&1; rc=$?
if [[ $MODE == *"lint"* ]]; then
test $rc -eq 0 && dolint 1>>/var/www/gsi-current.html 2>&1; lint_rc=$?
fi
test $rc -eq 0 && dotest 1>>/var/www/gsi-current.html 2>&1; rc=$?
echo '</pre>' >> /var/www/gsi-current.html
if [ $rc -eq 0 ]; then status=pass; else status=fail; fi
echo '<pre>' >> /var/www/gsi-current.html
gzip ${WORKSPACE}/logs.tar 2>&1 1>/dev/null
echo "Version: <a href='versions-$TS.cfg'>versions-$TS.cfg</a>" >> /var/www/gsi-current.html
echo "Build Log: <a href='make-$TS.log'>make-$TS.log</a>" >> /var/www/gsi-current.html
echo "Server Log: <a href='logs-$TS.tar.gz'>logs-$TS.tar.gz</a>" >> /var/www/gsi-current.html
echo "</pre><h1>Finished</h1></body></html>" >> /var/www/gsi-current.html
cp  /var/www/gsi-current.html /var/www/gsi-$TS.$status.html
mv ${WORKSPACE}/make.log /var/www/make-$TS.log
mv ${WORKSPACE}/logs.tar.gz /var/www/logs-$TS.tar.gz
mv ${WORKSPACE}/versions.cfg /var/www/versions-$TS.cfg
case "$STORAGE" in
  "plasma") export STORAGE="memdb"  ;;
  "memdb")  export STORAGE="fdb"    ;;
  "fdb")    export STORAGE="plasma" ;;
  *)        export STORAGE="plasma" ;;
esac
perl -pi -e "s/export STORAGE=.*/export STORAGE=$STORAGE/g" ~/.cienv
dowatch
