#!/bin/bash

source ~/.cienv

if [ "$STORAGE" = "" ]; then
  echo 'STORAGE not set'
  exit 2
fi

cd $WORKSPACE/goproj/src/github.com/couchbase/indexing
gover="`grep -A20 'TARGET cbindex PACKAGE' CMakeLists.txt  | grep GOVERSION | head -1 | sed 's/^.*\([0-9]\.[0-9].[0-9]\).*$/\1/'`"
export GOROOT=$HOME/.cbdepscache/exploded/x86_64/go-$gover/go
export PATH=$PATH:$GOROOT/bin

cd $HOME/bin
go run perfstat.go /var/www/gsi-$STORAGE-*.perf.html > /tmp/timing.html
cat /tmp/timing.html > /var/www/timing-$STORAGE.html
