#!/bin/bash

cd /var/www
> /tmp/timing.html
> /tmp/timing.data

exit 0

for i in `ls -t timing-*.log`; do
  len="`wc -l $i | awk '{print $1}'`"
  if [ "$len" -lt 5 ]; then continue; fi
  join -a1 -a2 -o auto -e '?' /tmp/timing.data $i > /tmp/timing.out
  mv /tmp/timing.out /tmp/timing.data
done

cat >>/tmp/timing.html <<'EOF'
<!DOCTYPE html>
<html>
<head>
  <title>Sherlock Timing</title>
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.4/css/jquery.dataTables.css">
  <script type="text/javascript" src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <script type="text/javascript" src="//cdn.datatables.net/1.10.4/js/jquery.dataTables.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery-csv/0.71/jquery.csv-0.71.min.js"></script>
  <script type="text/javascript" src="https://www.google.com/jsapi?autoload={'modules':[{'name':'visualization','version':'1','packages':['corechart']}]}"></script>

  <script type="text/javascript">
    $(document).ready(function() {
      ssv = $("#data").val();

      traw = $.csv.toArrays(ssv, {"separator":" "});
      theader = traw[0];
      tdata = traw.slice(1);
      tcols = [];
      for (i=0; i<theader.length; i++) {
        ver = "<a href='sherlock-" + theader[i] + ".htm'>" + theader[i] + "</a>"
        tcols.push({"title": ver});
      }
      for (i=0; i<tdata.length; i++) {
        tele = tdata[i][0];
        tlink = "<a href='#chart" + (i+1) + "'>" + tele + "</a>";
        tdata[i][0] = tlink;
      }
      $("#timing").DataTable({
         "data":     tdata, 
         "columns":  tcols,
         "paging":   false,
         "ordering": false,
         "info":     false,
      });

      craw = $.csv.toArrays(ssv, {"separator":" "});
      cxarr = craw[0];
      for (t=1; t<craw.length; t++) {
        cyarr = craw[t];
        cdata = [["Timestamp", "Value"]];
        for (i=cxarr.length-1; i>0; i--) {
          cx = craw[0][i]
          cy = parseFloat(craw[t][i])
          if (!isNaN(cy)) cdata.push([cx, cy]);
        }
        gdata = google.visualization.arrayToDataTable(cdata);
        cele = cyarr[0];
        cele = cele.replace(/([A-Z0-9])/g, " $1");
        cele = cele.replace("_", ": ");
        gopt = {title: cele, hAxis: {title: "Build"}, vAxis: {title: "Runtime (sec)"}, legend: {position: "none"}};
        clink = "<a name='chart" + t + "'></a>";
        cdiv =  "<div id='chart" + t +"'></div>";
        $("#charts").append(clink);
        $("#charts").append(cdiv);
        chart = new google.visualization.LineChart($("#chart"+t)[0]);
        chart.draw(gdata, gopt);
      }
    });
  </script>
  <style>
    a:link { color: DarkBlue; }
    a:visited { color: DarkBlue; }
  </style>
</head>
<body>
  <table id="timing" class="display"></table>
  <p/>
  <div id="charts" style="width: 80%; height: 600px"></div>
EOF

echo '<textarea id="data" style="display:none">' >> /tmp/timing.html
cat /tmp/timing.data >> /tmp/timing.html
echo '</textarea></body></html>' >> /tmp/timing.html
mv /tmp/timing.html /var/www/sherlock-timing.html

