#!/bin/bash

source ~/.cienv

if [ "$WORKSPACE" = "" ]; then
  echo 'WORKSPACE not set'
  exit 2
fi

if [ "$STORAGE" = "memdb" ]; then
  exit 0
fi

for i in {1..60}; do
  cd $WORKSPACE
  sleep 60

  current="`git ls-remote git://github.com/couchbase/indexing $BRANCH | awk '{print $1}'`"
  good="`cat ~/indexing.good`"
  if [ "$current" != "$good" ]; then exit 0; fi

done

