// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Error message can be sent back as response or
// encapsulated in response packets.
type Error struct {
	Error                *string  `protobuf:"bytes,1,req,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

// list of vbucket numbers
type Vbuckets struct {
	Vbnos                []uint32 `protobuf:"varint,1,rep,name=vbnos" json:"vbnos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vbuckets) Reset()         { *m = Vbuckets{} }
func (m *Vbuckets) String() string { return proto.CompactTextString(m) }
func (*Vbuckets) ProtoMessage()    {}
func (*Vbuckets) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Vbuckets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vbuckets.Unmarshal(m, b)
}
func (m *Vbuckets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vbuckets.Marshal(b, m, deterministic)
}
func (m *Vbuckets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vbuckets.Merge(m, src)
}
func (m *Vbuckets) XXX_Size() int {
	return xxx_messageInfo_Vbuckets.Size(m)
}
func (m *Vbuckets) XXX_DiscardUnknown() {
	xxx_messageInfo_Vbuckets.DiscardUnknown(m)
}

var xxx_messageInfo_Vbuckets proto.InternalMessageInfo

func (m *Vbuckets) GetVbnos() []uint32 {
	if m != nil {
		return m.Vbnos
	}
	return nil
}

// Start and end of DCP snapshot
type Snapshot struct {
	Start                *uint64  `protobuf:"varint,1,req,name=start" json:"start,omitempty"`
	End                  *uint64  `protobuf:"varint,2,req,name=end" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Snapshot.Unmarshal(m, b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
}
func (m *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(m, src)
}
func (m *Snapshot) XXX_Size() int {
	return xxx_messageInfo_Snapshot.Size(m)
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetStart() uint64 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return 0
}

func (m *Snapshot) GetEnd() uint64 {
	if m != nil && m.End != nil {
		return *m.End
	}
	return 0
}

// logical clock for a subset of vbuckets
type TsVb struct {
	Pool                 *string  `protobuf:"bytes,1,req,name=pool" json:"pool,omitempty"`
	Bucket               *string  `protobuf:"bytes,2,req,name=bucket" json:"bucket,omitempty"`
	Vbnos                []uint32 `protobuf:"varint,3,rep,name=vbnos" json:"vbnos,omitempty"`
	Seqnos               []uint64 `protobuf:"varint,4,rep,name=seqnos" json:"seqnos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TsVb) Reset()         { *m = TsVb{} }
func (m *TsVb) String() string { return proto.CompactTextString(m) }
func (*TsVb) ProtoMessage()    {}
func (*TsVb) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *TsVb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TsVb.Unmarshal(m, b)
}
func (m *TsVb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TsVb.Marshal(b, m, deterministic)
}
func (m *TsVb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TsVb.Merge(m, src)
}
func (m *TsVb) XXX_Size() int {
	return xxx_messageInfo_TsVb.Size(m)
}
func (m *TsVb) XXX_DiscardUnknown() {
	xxx_messageInfo_TsVb.DiscardUnknown(m)
}

var xxx_messageInfo_TsVb proto.InternalMessageInfo

func (m *TsVb) GetPool() string {
	if m != nil && m.Pool != nil {
		return *m.Pool
	}
	return ""
}

func (m *TsVb) GetBucket() string {
	if m != nil && m.Bucket != nil {
		return *m.Bucket
	}
	return ""
}

func (m *TsVb) GetVbnos() []uint32 {
	if m != nil {
		return m.Vbnos
	}
	return nil
}

func (m *TsVb) GetSeqnos() []uint64 {
	if m != nil {
		return m.Seqnos
	}
	return nil
}

// logical clock for full set of vbuckets, starting from 0 to MaxVbucket.
type TsVbFull struct {
	Pool                 *string  `protobuf:"bytes,1,req,name=pool" json:"pool,omitempty"`
	Bucket               *string  `protobuf:"bytes,2,req,name=bucket" json:"bucket,omitempty"`
	Seqnos               []uint64 `protobuf:"varint,3,rep,name=seqnos" json:"seqnos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TsVbFull) Reset()         { *m = TsVbFull{} }
func (m *TsVbFull) String() string { return proto.CompactTextString(m) }
func (*TsVbFull) ProtoMessage()    {}
func (*TsVbFull) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *TsVbFull) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TsVbFull.Unmarshal(m, b)
}
func (m *TsVbFull) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TsVbFull.Marshal(b, m, deterministic)
}
func (m *TsVbFull) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TsVbFull.Merge(m, src)
}
func (m *TsVbFull) XXX_Size() int {
	return xxx_messageInfo_TsVbFull.Size(m)
}
func (m *TsVbFull) XXX_DiscardUnknown() {
	xxx_messageInfo_TsVbFull.DiscardUnknown(m)
}

var xxx_messageInfo_TsVbFull proto.InternalMessageInfo

func (m *TsVbFull) GetPool() string {
	if m != nil && m.Pool != nil {
		return *m.Pool
	}
	return ""
}

func (m *TsVbFull) GetBucket() string {
	if m != nil && m.Bucket != nil {
		return *m.Bucket
	}
	return ""
}

func (m *TsVbFull) GetSeqnos() []uint64 {
	if m != nil {
		return m.Seqnos
	}
	return nil
}

// logical clock for a subset of vbuckets along with branch-id and snapshot
// information.
type TsVbuuid struct {
	Pool                 *string     `protobuf:"bytes,1,req,name=pool" json:"pool,omitempty"`
	Bucket               *string     `protobuf:"bytes,2,req,name=bucket" json:"bucket,omitempty"`
	Vbnos                []uint32    `protobuf:"varint,3,rep,name=vbnos" json:"vbnos,omitempty"`
	Seqnos               []uint64    `protobuf:"varint,4,rep,name=seqnos" json:"seqnos,omitempty"`
	Vbuuids              []uint64    `protobuf:"varint,5,rep,name=vbuuids" json:"vbuuids,omitempty"`
	Snapshots            []*Snapshot `protobuf:"bytes,6,rep,name=snapshots" json:"snapshots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TsVbuuid) Reset()         { *m = TsVbuuid{} }
func (m *TsVbuuid) String() string { return proto.CompactTextString(m) }
func (*TsVbuuid) ProtoMessage()    {}
func (*TsVbuuid) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *TsVbuuid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TsVbuuid.Unmarshal(m, b)
}
func (m *TsVbuuid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TsVbuuid.Marshal(b, m, deterministic)
}
func (m *TsVbuuid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TsVbuuid.Merge(m, src)
}
func (m *TsVbuuid) XXX_Size() int {
	return xxx_messageInfo_TsVbuuid.Size(m)
}
func (m *TsVbuuid) XXX_DiscardUnknown() {
	xxx_messageInfo_TsVbuuid.DiscardUnknown(m)
}

var xxx_messageInfo_TsVbuuid proto.InternalMessageInfo

func (m *TsVbuuid) GetPool() string {
	if m != nil && m.Pool != nil {
		return *m.Pool
	}
	return ""
}

func (m *TsVbuuid) GetBucket() string {
	if m != nil && m.Bucket != nil {
		return *m.Bucket
	}
	return ""
}

func (m *TsVbuuid) GetVbnos() []uint32 {
	if m != nil {
		return m.Vbnos
	}
	return nil
}

func (m *TsVbuuid) GetSeqnos() []uint64 {
	if m != nil {
		return m.Seqnos
	}
	return nil
}

func (m *TsVbuuid) GetVbuuids() []uint64 {
	if m != nil {
		return m.Vbuuids
	}
	return nil
}

func (m *TsVbuuid) GetSnapshots() []*Snapshot {
	if m != nil {
		return m.Snapshots
	}
	return nil
}

// failover log for a vbucket.
type FailoverLog struct {
	Vbno                 *uint32  `protobuf:"varint,1,req,name=vbno" json:"vbno,omitempty"`
	Vbuuids              []uint64 `protobuf:"varint,2,rep,name=vbuuids" json:"vbuuids,omitempty"`
	Seqnos               []uint64 `protobuf:"varint,3,rep,name=seqnos" json:"seqnos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailoverLog) Reset()         { *m = FailoverLog{} }
func (m *FailoverLog) String() string { return proto.CompactTextString(m) }
func (*FailoverLog) ProtoMessage()    {}
func (*FailoverLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{6}
}

func (m *FailoverLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailoverLog.Unmarshal(m, b)
}
func (m *FailoverLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailoverLog.Marshal(b, m, deterministic)
}
func (m *FailoverLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailoverLog.Merge(m, src)
}
func (m *FailoverLog) XXX_Size() int {
	return xxx_messageInfo_FailoverLog.Size(m)
}
func (m *FailoverLog) XXX_DiscardUnknown() {
	xxx_messageInfo_FailoverLog.DiscardUnknown(m)
}

var xxx_messageInfo_FailoverLog proto.InternalMessageInfo

func (m *FailoverLog) GetVbno() uint32 {
	if m != nil && m.Vbno != nil {
		return *m.Vbno
	}
	return 0
}

func (m *FailoverLog) GetVbuuids() []uint64 {
	if m != nil {
		return m.Vbuuids
	}
	return nil
}

func (m *FailoverLog) GetSeqnos() []uint64 {
	if m != nil {
		return m.Seqnos
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "protobuf.Error")
	proto.RegisterType((*Vbuckets)(nil), "protobuf.Vbuckets")
	proto.RegisterType((*Snapshot)(nil), "protobuf.Snapshot")
	proto.RegisterType((*TsVb)(nil), "protobuf.TsVb")
	proto.RegisterType((*TsVbFull)(nil), "protobuf.TsVbFull")
	proto.RegisterType((*TsVbuuid)(nil), "protobuf.TsVbuuid")
	proto.RegisterType((*FailoverLog)(nil), "protobuf.FailoverLog")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x90, 0xb1, 0x4f, 0xf3, 0x30,
	0x10, 0xc5, 0xd5, 0xd8, 0xe9, 0x97, 0x5c, 0x9a, 0x0f, 0xc9, 0x03, 0x32, 0x5b, 0x64, 0x09, 0x94,
	0x29, 0x03, 0x13, 0x03, 0x1b, 0xa2, 0x13, 0x1b, 0xa8, 0x7b, 0xd2, 0x1a, 0xa8, 0x48, 0x73, 0xc1,
	0x67, 0x67, 0xe5, 0x5f, 0x47, 0xe7, 0x50, 0x15, 0xb1, 0x30, 0x30, 0xd9, 0xe7, 0xe7, 0xf7, 0xbb,
	0xa7, 0x07, 0xab, 0x2d, 0x1e, 0x0e, 0x38, 0x34, 0xa3, 0x43, 0x8f, 0x2a, 0x8b, 0x47, 0x17, 0x9e,
	0xcd, 0x39, 0xa4, 0xf7, 0xce, 0xa1, 0x53, 0x25, 0xa4, 0x96, 0x2f, 0x7a, 0x51, 0x25, 0x75, 0x6e,
	0x2e, 0x20, 0xdb, 0x74, 0x61, 0xfb, 0x66, 0x3d, 0xb1, 0x34, 0x75, 0x03, 0x92, 0x5e, 0x54, 0xa2,
	0x2e, 0xcd, 0x15, 0x64, 0x8f, 0x43, 0x3b, 0xd2, 0x2b, 0x7a, 0x96, 0xc8, 0xb7, 0xce, 0x47, 0x97,
	0x54, 0x05, 0x08, 0x3b, 0xec, 0x74, 0xc2, 0x83, 0xb9, 0x03, 0xf9, 0x44, 0x9b, 0x4e, 0xad, 0x40,
	0x8e, 0x88, 0xfd, 0x0c, 0x56, 0xff, 0x61, 0x39, 0x73, 0xe3, 0xaf, 0xfc, 0x04, 0x17, 0x0c, 0x67,
	0x99, 0xec, 0x3b, 0xcf, 0xb2, 0x12, 0xb5, 0x34, 0x37, 0x90, 0x31, 0x64, 0x1d, 0xfa, 0xfe, 0x17,
	0xd0, 0xc9, 0x29, 0xa2, 0xf3, 0x63, 0x76, 0x86, 0xb0, 0xdf, 0xfd, 0x29, 0x82, 0x3a, 0x83, 0x7f,
	0x53, 0xc4, 0x90, 0x4e, 0xe3, 0xc3, 0x25, 0xe4, 0xf4, 0x55, 0x00, 0xe9, 0x65, 0x25, 0xea, 0xe2,
	0x5a, 0x35, 0xc7, 0x46, 0x9b, 0x63, 0x37, 0xe6, 0x16, 0x8a, 0x75, 0xbb, 0xef, 0x71, 0xb2, 0xee,
	0x01, 0x5f, 0x38, 0x03, 0x6f, 0x89, 0x19, 0xca, 0xef, 0xd0, 0x24, 0x42, 0x7f, 0xc4, 0xff, 0x0c,
	0x00, 0x00, 0xff, 0xff, 0xce, 0x53, 0x93, 0xf0, 0xb1, 0x01, 0x00, 0x00,
}
