// Code generated by protoc-gen-go. DO NOT EDIT.
// source: partn_single.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// SinglePartition is an oxymoron - the purpose of partition is to
// scale-out, but using this partition-scheme for an index means the full
// data set is kept on the same node.
type SinglePartition struct {
	Endpoints            []string `protobuf:"bytes,1,rep,name=endpoints" json:"endpoints,omitempty"`
	CoordEndpoint        *string  `protobuf:"bytes,2,opt,name=coordEndpoint" json:"coordEndpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SinglePartition) Reset()         { *m = SinglePartition{} }
func (m *SinglePartition) String() string { return proto.CompactTextString(m) }
func (*SinglePartition) ProtoMessage()    {}
func (*SinglePartition) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c1f2735407372dd, []int{0}
}

func (m *SinglePartition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SinglePartition.Unmarshal(m, b)
}
func (m *SinglePartition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SinglePartition.Marshal(b, m, deterministic)
}
func (m *SinglePartition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SinglePartition.Merge(m, src)
}
func (m *SinglePartition) XXX_Size() int {
	return xxx_messageInfo_SinglePartition.Size(m)
}
func (m *SinglePartition) XXX_DiscardUnknown() {
	xxx_messageInfo_SinglePartition.DiscardUnknown(m)
}

var xxx_messageInfo_SinglePartition proto.InternalMessageInfo

func (m *SinglePartition) GetEndpoints() []string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *SinglePartition) GetCoordEndpoint() string {
	if m != nil && m.CoordEndpoint != nil {
		return *m.CoordEndpoint
	}
	return ""
}

func init() {
	proto.RegisterType((*SinglePartition)(nil), "protobuf.SinglePartition")
}

func init() { proto.RegisterFile("partn_single.proto", fileDescriptor_2c1f2735407372dd) }

var fileDescriptor_2c1f2735407372dd = []byte{
	// 103 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x48, 0x2c, 0x2a,
	0xc9, 0x8b, 0x2f, 0xce, 0xcc, 0x4b, 0xcf, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0xd6, 0x5c, 0xfc, 0xc1, 0x60, 0x99, 0x80, 0xc4, 0xa2, 0x92,
	0xcc, 0x92, 0xcc, 0xfc, 0x3c, 0x21, 0x41, 0x2e, 0xce, 0xd4, 0xbc, 0x94, 0x82, 0xfc, 0xcc, 0xbc,
	0x92, 0x62, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x4e, 0x21, 0x51, 0x2e, 0xde, 0xe4, 0xfc, 0xfc, 0xa2,
	0x14, 0x57, 0xa8, 0xb8, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x27, 0x20, 0x00, 0x00, 0xff, 0xff, 0x0a,
	0xe8, 0x36, 0x61, 0x5b, 0x00, 0x00, 0x00,
}
