// Code generated by protoc-gen-go. DO NOT EDIT.
// source: partn_tp.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Example TestPartition, can be used during development.
type TestPartition struct {
	Endpoints            []string `protobuf:"bytes,1,rep,name=endpoints" json:"endpoints,omitempty"`
	CoordEndpoint        *string  `protobuf:"bytes,2,opt,name=coordEndpoint" json:"coordEndpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestPartition) Reset()         { *m = TestPartition{} }
func (m *TestPartition) String() string { return proto.CompactTextString(m) }
func (*TestPartition) ProtoMessage()    {}
func (*TestPartition) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e0606a6c8b2cd62, []int{0}
}

func (m *TestPartition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestPartition.Unmarshal(m, b)
}
func (m *TestPartition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestPartition.Marshal(b, m, deterministic)
}
func (m *TestPartition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestPartition.Merge(m, src)
}
func (m *TestPartition) XXX_Size() int {
	return xxx_messageInfo_TestPartition.Size(m)
}
func (m *TestPartition) XXX_DiscardUnknown() {
	xxx_messageInfo_TestPartition.DiscardUnknown(m)
}

var xxx_messageInfo_TestPartition proto.InternalMessageInfo

func (m *TestPartition) GetEndpoints() []string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *TestPartition) GetCoordEndpoint() string {
	if m != nil && m.CoordEndpoint != nil {
		return *m.CoordEndpoint
	}
	return ""
}

func init() {
	proto.RegisterType((*TestPartition)(nil), "protobuf.TestPartition")
}

func init() { proto.RegisterFile("partn_tp.proto", fileDescriptor_7e0606a6c8b2cd62) }

var fileDescriptor_7e0606a6c8b2cd62 = []byte{
	// 101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x48, 0x2c, 0x2a,
	0xc9, 0x8b, 0x2f, 0x29, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5,
	0x69, 0x4a, 0x96, 0x5c, 0xbc, 0x21, 0xa9, 0xc5, 0x25, 0x01, 0x89, 0x45, 0x25, 0x99, 0x25, 0x99,
	0xf9, 0x79, 0x42, 0x82, 0x5c, 0x9c, 0xa9, 0x79, 0x29, 0x05, 0xf9, 0x99, 0x79, 0x25, 0xc5, 0x12,
	0x8c, 0x0a, 0xcc, 0x1a, 0x9c, 0x42, 0xa2, 0x5c, 0xbc, 0xc9, 0xf9, 0xf9, 0x45, 0x29, 0xae, 0x50,
	0x71, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x4e, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x11, 0x8b, 0x92,
	0x1d, 0x55, 0x00, 0x00, 0x00,
}
