// Code generated by protoc-gen-go. DO NOT EDIT.
// source: partn_key.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KeyPartition struct {
	NumPartition         *uint64  `protobuf:"varint,1,req,name=numPartition" json:"numPartition,omitempty"`
	Partitions           []uint64 `protobuf:"varint,2,rep,name=partitions" json:"partitions,omitempty"`
	Endpoints            []string `protobuf:"bytes,3,rep,name=endpoints" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyPartition) Reset()         { *m = KeyPartition{} }
func (m *KeyPartition) String() string { return proto.CompactTextString(m) }
func (*KeyPartition) ProtoMessage()    {}
func (*KeyPartition) Descriptor() ([]byte, []int) {
	return fileDescriptor_721f8bef372eaf5e, []int{0}
}

func (m *KeyPartition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyPartition.Unmarshal(m, b)
}
func (m *KeyPartition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyPartition.Marshal(b, m, deterministic)
}
func (m *KeyPartition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyPartition.Merge(m, src)
}
func (m *KeyPartition) XXX_Size() int {
	return xxx_messageInfo_KeyPartition.Size(m)
}
func (m *KeyPartition) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyPartition.DiscardUnknown(m)
}

var xxx_messageInfo_KeyPartition proto.InternalMessageInfo

func (m *KeyPartition) GetNumPartition() uint64 {
	if m != nil && m.NumPartition != nil {
		return *m.NumPartition
	}
	return 0
}

func (m *KeyPartition) GetPartitions() []uint64 {
	if m != nil {
		return m.Partitions
	}
	return nil
}

func (m *KeyPartition) GetEndpoints() []string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func init() {
	proto.RegisterType((*KeyPartition)(nil), "protobuf.KeyPartition")
}

func init() { proto.RegisterFile("partn_key.proto", fileDescriptor_721f8bef372eaf5e) }

var fileDescriptor_721f8bef372eaf5e = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x48, 0x2c, 0x2a,
	0xc9, 0x8b, 0xcf, 0x4e, 0xad, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49,
	0xa5, 0x69, 0x4a, 0xde, 0x5c, 0x3c, 0xde, 0xa9, 0x95, 0x01, 0x89, 0x45, 0x25, 0x99, 0x25, 0x99,
	0xf9, 0x79, 0x42, 0x22, 0x5c, 0x3c, 0x79, 0xa5, 0xb9, 0x70, 0xbe, 0x04, 0xa3, 0x02, 0x93, 0x06,
	0x8b, 0x90, 0x10, 0x17, 0x57, 0x01, 0x4c, 0xa8, 0x58, 0x82, 0x49, 0x81, 0x59, 0x83, 0x45, 0x48,
	0x90, 0x8b, 0x33, 0x35, 0x2f, 0xa5, 0x20, 0x3f, 0x33, 0xaf, 0xa4, 0x58, 0x82, 0x59, 0x81, 0x59,
	0x83, 0x13, 0x10, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x10, 0x86, 0x32, 0x68, 0x00, 0x00, 0x00,
}
