// Code generated by protoc-gen-go. DO NOT EDIT.
// source: projector.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FeedVersion int32

const (
	FeedVersion_sherlock FeedVersion = 1
	FeedVersion_watson   FeedVersion = 2
)

var FeedVersion_name = map[int32]string{
	1: "sherlock",
	2: "watson",
}

var FeedVersion_value = map[string]int32{
	"sherlock": 1,
	"watson":   2,
}

func (x FeedVersion) Enum() *FeedVersion {
	p := new(FeedVersion)
	*p = x
	return p
}

func (x FeedVersion) String() string {
	return proto.EnumName(FeedVersion_name, int32(x))
}

func (x *FeedVersion) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FeedVersion_value, data, "FeedVersion")
	if err != nil {
		return err
	}
	*x = FeedVersion(value)
	return nil
}

func (FeedVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{0}
}

// Requested by Coordinator/indexer to learn vbuckets
// hosted by kvnodes.
type VbmapRequest struct {
	Pool                 *string  `protobuf:"bytes,1,req,name=pool" json:"pool,omitempty"`
	Bucket               *string  `protobuf:"bytes,2,req,name=bucket" json:"bucket,omitempty"`
	Kvaddrs              []string `protobuf:"bytes,3,rep,name=kvaddrs" json:"kvaddrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VbmapRequest) Reset()         { *m = VbmapRequest{} }
func (m *VbmapRequest) String() string { return proto.CompactTextString(m) }
func (*VbmapRequest) ProtoMessage()    {}
func (*VbmapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{0}
}

func (m *VbmapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VbmapRequest.Unmarshal(m, b)
}
func (m *VbmapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VbmapRequest.Marshal(b, m, deterministic)
}
func (m *VbmapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VbmapRequest.Merge(m, src)
}
func (m *VbmapRequest) XXX_Size() int {
	return xxx_messageInfo_VbmapRequest.Size(m)
}
func (m *VbmapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VbmapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VbmapRequest proto.InternalMessageInfo

func (m *VbmapRequest) GetPool() string {
	if m != nil && m.Pool != nil {
		return *m.Pool
	}
	return ""
}

func (m *VbmapRequest) GetBucket() string {
	if m != nil && m.Bucket != nil {
		return *m.Bucket
	}
	return ""
}

func (m *VbmapRequest) GetKvaddrs() []string {
	if m != nil {
		return m.Kvaddrs
	}
	return nil
}

type VbmapResponse struct {
	Kvaddrs              []string    `protobuf:"bytes,1,rep,name=kvaddrs" json:"kvaddrs,omitempty"`
	Kvvbnos              []*Vbuckets `protobuf:"bytes,2,rep,name=kvvbnos" json:"kvvbnos,omitempty"`
	Err                  *Error      `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VbmapResponse) Reset()         { *m = VbmapResponse{} }
func (m *VbmapResponse) String() string { return proto.CompactTextString(m) }
func (*VbmapResponse) ProtoMessage()    {}
func (*VbmapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{1}
}

func (m *VbmapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VbmapResponse.Unmarshal(m, b)
}
func (m *VbmapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VbmapResponse.Marshal(b, m, deterministic)
}
func (m *VbmapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VbmapResponse.Merge(m, src)
}
func (m *VbmapResponse) XXX_Size() int {
	return xxx_messageInfo_VbmapResponse.Size(m)
}
func (m *VbmapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VbmapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VbmapResponse proto.InternalMessageInfo

func (m *VbmapResponse) GetKvaddrs() []string {
	if m != nil {
		return m.Kvaddrs
	}
	return nil
}

func (m *VbmapResponse) GetKvvbnos() []*Vbuckets {
	if m != nil {
		return m.Kvvbnos
	}
	return nil
}

func (m *VbmapResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

// Requested by Coordinator during system-start,
// re-connect, rollback
type FailoverLogRequest struct {
	Pool                 *string  `protobuf:"bytes,1,req,name=pool" json:"pool,omitempty"`
	Bucket               *string  `protobuf:"bytes,2,req,name=bucket" json:"bucket,omitempty"`
	Vbnos                []uint32 `protobuf:"varint,3,rep,name=vbnos" json:"vbnos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailoverLogRequest) Reset()         { *m = FailoverLogRequest{} }
func (m *FailoverLogRequest) String() string { return proto.CompactTextString(m) }
func (*FailoverLogRequest) ProtoMessage()    {}
func (*FailoverLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{2}
}

func (m *FailoverLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailoverLogRequest.Unmarshal(m, b)
}
func (m *FailoverLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailoverLogRequest.Marshal(b, m, deterministic)
}
func (m *FailoverLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailoverLogRequest.Merge(m, src)
}
func (m *FailoverLogRequest) XXX_Size() int {
	return xxx_messageInfo_FailoverLogRequest.Size(m)
}
func (m *FailoverLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FailoverLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FailoverLogRequest proto.InternalMessageInfo

func (m *FailoverLogRequest) GetPool() string {
	if m != nil && m.Pool != nil {
		return *m.Pool
	}
	return ""
}

func (m *FailoverLogRequest) GetBucket() string {
	if m != nil && m.Bucket != nil {
		return *m.Bucket
	}
	return ""
}

func (m *FailoverLogRequest) GetVbnos() []uint32 {
	if m != nil {
		return m.Vbnos
	}
	return nil
}

type FailoverLogResponse struct {
	Logs                 []*FailoverLog `protobuf:"bytes,1,rep,name=logs" json:"logs,omitempty"`
	Err                  *Error         `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FailoverLogResponse) Reset()         { *m = FailoverLogResponse{} }
func (m *FailoverLogResponse) String() string { return proto.CompactTextString(m) }
func (*FailoverLogResponse) ProtoMessage()    {}
func (*FailoverLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{3}
}

func (m *FailoverLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailoverLogResponse.Unmarshal(m, b)
}
func (m *FailoverLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailoverLogResponse.Marshal(b, m, deterministic)
}
func (m *FailoverLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailoverLogResponse.Merge(m, src)
}
func (m *FailoverLogResponse) XXX_Size() int {
	return xxx_messageInfo_FailoverLogResponse.Size(m)
}
func (m *FailoverLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FailoverLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FailoverLogResponse proto.InternalMessageInfo

func (m *FailoverLogResponse) GetLogs() []*FailoverLog {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *FailoverLogResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

// Requested by Coordinator or indexer to start a
// new mutation topic. Respond back with TopicResponse.
type MutationTopicRequest struct {
	Topic         *string     `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	EndpointType  *string     `protobuf:"bytes,2,req,name=endpointType" json:"endpointType,omitempty"`
	ReqTimestamps []*TsVbuuid `protobuf:"bytes,3,rep,name=reqTimestamps" json:"reqTimestamps,omitempty"`
	// initial list of instances applicable for this topic
	Instances            []*Instance  `protobuf:"bytes,4,rep,name=instances" json:"instances,omitempty"`
	Version              *FeedVersion `protobuf:"varint,5,opt,name=version,enum=protobuf.FeedVersion,def=1" json:"version,omitempty"`
	Async                *bool        `protobuf:"varint,6,opt,name=async" json:"async,omitempty"`
	Opaque2              *uint64      `protobuf:"varint,7,opt,name=opaque2" json:"opaque2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MutationTopicRequest) Reset()         { *m = MutationTopicRequest{} }
func (m *MutationTopicRequest) String() string { return proto.CompactTextString(m) }
func (*MutationTopicRequest) ProtoMessage()    {}
func (*MutationTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{4}
}

func (m *MutationTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutationTopicRequest.Unmarshal(m, b)
}
func (m *MutationTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutationTopicRequest.Marshal(b, m, deterministic)
}
func (m *MutationTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutationTopicRequest.Merge(m, src)
}
func (m *MutationTopicRequest) XXX_Size() int {
	return xxx_messageInfo_MutationTopicRequest.Size(m)
}
func (m *MutationTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MutationTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MutationTopicRequest proto.InternalMessageInfo

const Default_MutationTopicRequest_Version FeedVersion = FeedVersion_sherlock

func (m *MutationTopicRequest) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *MutationTopicRequest) GetEndpointType() string {
	if m != nil && m.EndpointType != nil {
		return *m.EndpointType
	}
	return ""
}

func (m *MutationTopicRequest) GetReqTimestamps() []*TsVbuuid {
	if m != nil {
		return m.ReqTimestamps
	}
	return nil
}

func (m *MutationTopicRequest) GetInstances() []*Instance {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *MutationTopicRequest) GetVersion() FeedVersion {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return Default_MutationTopicRequest_Version
}

func (m *MutationTopicRequest) GetAsync() bool {
	if m != nil && m.Async != nil {
		return *m.Async
	}
	return false
}

func (m *MutationTopicRequest) GetOpaque2() uint64 {
	if m != nil && m.Opaque2 != nil {
		return *m.Opaque2
	}
	return 0
}

// Response back for
// MutationTopicRequest, RestartVbucketsRequest, AddBucketsRequest
type TopicResponse struct {
	Topic                *string     `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
	InstanceIds          []uint64    `protobuf:"varint,2,rep,name=instanceIds" json:"instanceIds,omitempty"`
	ActiveTimestamps     []*TsVbuuid `protobuf:"bytes,3,rep,name=activeTimestamps" json:"activeTimestamps,omitempty"`
	RollbackTimestamps   []*TsVbuuid `protobuf:"bytes,4,rep,name=rollbackTimestamps" json:"rollbackTimestamps,omitempty"`
	Err                  *Error      `protobuf:"bytes,5,opt,name=err" json:"err,omitempty"`
	PendingTimestamps    []*TsVbuuid `protobuf:"bytes,6,rep,name=pendingTimestamps" json:"pendingTimestamps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TopicResponse) Reset()         { *m = TopicResponse{} }
func (m *TopicResponse) String() string { return proto.CompactTextString(m) }
func (*TopicResponse) ProtoMessage()    {}
func (*TopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{5}
}

func (m *TopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicResponse.Unmarshal(m, b)
}
func (m *TopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicResponse.Marshal(b, m, deterministic)
}
func (m *TopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicResponse.Merge(m, src)
}
func (m *TopicResponse) XXX_Size() int {
	return xxx_messageInfo_TopicResponse.Size(m)
}
func (m *TopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TopicResponse proto.InternalMessageInfo

func (m *TopicResponse) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *TopicResponse) GetInstanceIds() []uint64 {
	if m != nil {
		return m.InstanceIds
	}
	return nil
}

func (m *TopicResponse) GetActiveTimestamps() []*TsVbuuid {
	if m != nil {
		return m.ActiveTimestamps
	}
	return nil
}

func (m *TopicResponse) GetRollbackTimestamps() []*TsVbuuid {
	if m != nil {
		return m.RollbackTimestamps
	}
	return nil
}

func (m *TopicResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *TopicResponse) GetPendingTimestamps() []*TsVbuuid {
	if m != nil {
		return m.PendingTimestamps
	}
	return nil
}

// Response back for
// AddInstancesRequest
type TimestampResponse struct {
	Topic                *string     `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	CurrentTimestamps    []*TsVbuuid `protobuf:"bytes,2,rep,name=currentTimestamps" json:"currentTimestamps,omitempty"`
	Err                  *Error      `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TimestampResponse) Reset()         { *m = TimestampResponse{} }
func (m *TimestampResponse) String() string { return proto.CompactTextString(m) }
func (*TimestampResponse) ProtoMessage()    {}
func (*TimestampResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{6}
}

func (m *TimestampResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimestampResponse.Unmarshal(m, b)
}
func (m *TimestampResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimestampResponse.Marshal(b, m, deterministic)
}
func (m *TimestampResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimestampResponse.Merge(m, src)
}
func (m *TimestampResponse) XXX_Size() int {
	return xxx_messageInfo_TimestampResponse.Size(m)
}
func (m *TimestampResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TimestampResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TimestampResponse proto.InternalMessageInfo

func (m *TimestampResponse) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *TimestampResponse) GetCurrentTimestamps() []*TsVbuuid {
	if m != nil {
		return m.CurrentTimestamps
	}
	return nil
}

func (m *TimestampResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

// RestartVbucketsRequest will restart a subset
// of vbuckets for each specified buckets.
// Respond back with TopicResponse
type RestartVbucketsRequest struct {
	Topic                *string     `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	RestartTimestamps    []*TsVbuuid `protobuf:"bytes,2,rep,name=restartTimestamps" json:"restartTimestamps,omitempty"`
	Opaque2              *uint64     `protobuf:"varint,3,opt,name=opaque2" json:"opaque2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RestartVbucketsRequest) Reset()         { *m = RestartVbucketsRequest{} }
func (m *RestartVbucketsRequest) String() string { return proto.CompactTextString(m) }
func (*RestartVbucketsRequest) ProtoMessage()    {}
func (*RestartVbucketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{7}
}

func (m *RestartVbucketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestartVbucketsRequest.Unmarshal(m, b)
}
func (m *RestartVbucketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestartVbucketsRequest.Marshal(b, m, deterministic)
}
func (m *RestartVbucketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestartVbucketsRequest.Merge(m, src)
}
func (m *RestartVbucketsRequest) XXX_Size() int {
	return xxx_messageInfo_RestartVbucketsRequest.Size(m)
}
func (m *RestartVbucketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestartVbucketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestartVbucketsRequest proto.InternalMessageInfo

func (m *RestartVbucketsRequest) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *RestartVbucketsRequest) GetRestartTimestamps() []*TsVbuuid {
	if m != nil {
		return m.RestartTimestamps
	}
	return nil
}

func (m *RestartVbucketsRequest) GetOpaque2() uint64 {
	if m != nil && m.Opaque2 != nil {
		return *m.Opaque2
	}
	return 0
}

// ShutdownVbucketsRequest will shutdown a subset of vbuckets
// for each specified buckets. Respond back with TopicResponse
type ShutdownVbucketsRequest struct {
	Topic                *string     `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	ShutdownTimestamps   []*TsVbuuid `protobuf:"bytes,2,rep,name=shutdownTimestamps" json:"shutdownTimestamps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ShutdownVbucketsRequest) Reset()         { *m = ShutdownVbucketsRequest{} }
func (m *ShutdownVbucketsRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownVbucketsRequest) ProtoMessage()    {}
func (*ShutdownVbucketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{8}
}

func (m *ShutdownVbucketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownVbucketsRequest.Unmarshal(m, b)
}
func (m *ShutdownVbucketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownVbucketsRequest.Marshal(b, m, deterministic)
}
func (m *ShutdownVbucketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownVbucketsRequest.Merge(m, src)
}
func (m *ShutdownVbucketsRequest) XXX_Size() int {
	return xxx_messageInfo_ShutdownVbucketsRequest.Size(m)
}
func (m *ShutdownVbucketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownVbucketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownVbucketsRequest proto.InternalMessageInfo

func (m *ShutdownVbucketsRequest) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *ShutdownVbucketsRequest) GetShutdownTimestamps() []*TsVbuuid {
	if m != nil {
		return m.ShutdownTimestamps
	}
	return nil
}

// AddBucketsRequest will start vbucket-streams
// specified buckets and add them to the topic that
// has already started.
// Respond back with TopicResponse
type AddBucketsRequest struct {
	Topic         *string     `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	ReqTimestamps []*TsVbuuid `protobuf:"bytes,2,rep,name=reqTimestamps" json:"reqTimestamps,omitempty"`
	// list of instances applicable for buckets.
	Instances            []*Instance  `protobuf:"bytes,3,rep,name=instances" json:"instances,omitempty"`
	Version              *FeedVersion `protobuf:"varint,4,opt,name=version,enum=protobuf.FeedVersion,def=1" json:"version,omitempty"`
	Opaque2              *uint64      `protobuf:"varint,5,opt,name=opaque2" json:"opaque2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddBucketsRequest) Reset()         { *m = AddBucketsRequest{} }
func (m *AddBucketsRequest) String() string { return proto.CompactTextString(m) }
func (*AddBucketsRequest) ProtoMessage()    {}
func (*AddBucketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{9}
}

func (m *AddBucketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBucketsRequest.Unmarshal(m, b)
}
func (m *AddBucketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBucketsRequest.Marshal(b, m, deterministic)
}
func (m *AddBucketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBucketsRequest.Merge(m, src)
}
func (m *AddBucketsRequest) XXX_Size() int {
	return xxx_messageInfo_AddBucketsRequest.Size(m)
}
func (m *AddBucketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBucketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBucketsRequest proto.InternalMessageInfo

const Default_AddBucketsRequest_Version FeedVersion = FeedVersion_sherlock

func (m *AddBucketsRequest) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *AddBucketsRequest) GetReqTimestamps() []*TsVbuuid {
	if m != nil {
		return m.ReqTimestamps
	}
	return nil
}

func (m *AddBucketsRequest) GetInstances() []*Instance {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *AddBucketsRequest) GetVersion() FeedVersion {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return Default_AddBucketsRequest_Version
}

func (m *AddBucketsRequest) GetOpaque2() uint64 {
	if m != nil && m.Opaque2 != nil {
		return *m.Opaque2
	}
	return 0
}

// DelBucketsRequest will shutdown vbucket-streams
// for specified buckets and remove the buckets from topic.
// Respond back with TopicResponse
type DelBucketsRequest struct {
	Topic                *string  `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	Buckets              []string `protobuf:"bytes,2,rep,name=buckets" json:"buckets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelBucketsRequest) Reset()         { *m = DelBucketsRequest{} }
func (m *DelBucketsRequest) String() string { return proto.CompactTextString(m) }
func (*DelBucketsRequest) ProtoMessage()    {}
func (*DelBucketsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{10}
}

func (m *DelBucketsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelBucketsRequest.Unmarshal(m, b)
}
func (m *DelBucketsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelBucketsRequest.Marshal(b, m, deterministic)
}
func (m *DelBucketsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelBucketsRequest.Merge(m, src)
}
func (m *DelBucketsRequest) XXX_Size() int {
	return xxx_messageInfo_DelBucketsRequest.Size(m)
}
func (m *DelBucketsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelBucketsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelBucketsRequest proto.InternalMessageInfo

func (m *DelBucketsRequest) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *DelBucketsRequest) GetBuckets() []string {
	if m != nil {
		return m.Buckets
	}
	return nil
}

// AddInstancesRequest to add index-instances to a topic.
// Respond back with TimestampResponse
type AddInstancesRequest struct {
	Topic                *string      `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	Instances            []*Instance  `protobuf:"bytes,2,rep,name=instances" json:"instances,omitempty"`
	Version              *FeedVersion `protobuf:"varint,3,opt,name=version,enum=protobuf.FeedVersion,def=1" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddInstancesRequest) Reset()         { *m = AddInstancesRequest{} }
func (m *AddInstancesRequest) String() string { return proto.CompactTextString(m) }
func (*AddInstancesRequest) ProtoMessage()    {}
func (*AddInstancesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{11}
}

func (m *AddInstancesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddInstancesRequest.Unmarshal(m, b)
}
func (m *AddInstancesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddInstancesRequest.Marshal(b, m, deterministic)
}
func (m *AddInstancesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddInstancesRequest.Merge(m, src)
}
func (m *AddInstancesRequest) XXX_Size() int {
	return xxx_messageInfo_AddInstancesRequest.Size(m)
}
func (m *AddInstancesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddInstancesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddInstancesRequest proto.InternalMessageInfo

const Default_AddInstancesRequest_Version FeedVersion = FeedVersion_sherlock

func (m *AddInstancesRequest) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *AddInstancesRequest) GetInstances() []*Instance {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *AddInstancesRequest) GetVersion() FeedVersion {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return Default_AddInstancesRequest_Version
}

// DelInstancesRequest to add index-instances to a topic.
// Respond back with TopicResponse
type DelInstancesRequest struct {
	Topic                *string  `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	InstanceIds          []uint64 `protobuf:"varint,2,rep,name=instanceIds" json:"instanceIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelInstancesRequest) Reset()         { *m = DelInstancesRequest{} }
func (m *DelInstancesRequest) String() string { return proto.CompactTextString(m) }
func (*DelInstancesRequest) ProtoMessage()    {}
func (*DelInstancesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{12}
}

func (m *DelInstancesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelInstancesRequest.Unmarshal(m, b)
}
func (m *DelInstancesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelInstancesRequest.Marshal(b, m, deterministic)
}
func (m *DelInstancesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelInstancesRequest.Merge(m, src)
}
func (m *DelInstancesRequest) XXX_Size() int {
	return xxx_messageInfo_DelInstancesRequest.Size(m)
}
func (m *DelInstancesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelInstancesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelInstancesRequest proto.InternalMessageInfo

func (m *DelInstancesRequest) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *DelInstancesRequest) GetInstanceIds() []uint64 {
	if m != nil {
		return m.InstanceIds
	}
	return nil
}

// Requested by indexer / coordinator to inform router to re-connect with
// downstream endpoint. Error message will be sent as response.
type RepairEndpointsRequest struct {
	Topic                *string  `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	Endpoints            []string `protobuf:"bytes,2,rep,name=endpoints" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepairEndpointsRequest) Reset()         { *m = RepairEndpointsRequest{} }
func (m *RepairEndpointsRequest) String() string { return proto.CompactTextString(m) }
func (*RepairEndpointsRequest) ProtoMessage()    {}
func (*RepairEndpointsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{13}
}

func (m *RepairEndpointsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepairEndpointsRequest.Unmarshal(m, b)
}
func (m *RepairEndpointsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepairEndpointsRequest.Marshal(b, m, deterministic)
}
func (m *RepairEndpointsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepairEndpointsRequest.Merge(m, src)
}
func (m *RepairEndpointsRequest) XXX_Size() int {
	return xxx_messageInfo_RepairEndpointsRequest.Size(m)
}
func (m *RepairEndpointsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RepairEndpointsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RepairEndpointsRequest proto.InternalMessageInfo

func (m *RepairEndpointsRequest) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *RepairEndpointsRequest) GetEndpoints() []string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

// Requested by coordinator to should down a mutation topic and all KV
// connections active for that topic. Error message will be sent as response.
type ShutdownTopicRequest struct {
	Topic                *string  `protobuf:"bytes,1,req,name=topic" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownTopicRequest) Reset()         { *m = ShutdownTopicRequest{} }
func (m *ShutdownTopicRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownTopicRequest) ProtoMessage()    {}
func (*ShutdownTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{14}
}

func (m *ShutdownTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownTopicRequest.Unmarshal(m, b)
}
func (m *ShutdownTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownTopicRequest.Marshal(b, m, deterministic)
}
func (m *ShutdownTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownTopicRequest.Merge(m, src)
}
func (m *ShutdownTopicRequest) XXX_Size() int {
	return xxx_messageInfo_ShutdownTopicRequest.Size(m)
}
func (m *ShutdownTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownTopicRequest proto.InternalMessageInfo

func (m *ShutdownTopicRequest) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

// Generic instance, can be an index instance, xdcr, search etc ...
type Instance struct {
	IndexInstance        *IndexInst `protobuf:"bytes,1,opt,name=indexInstance" json:"indexInstance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{15}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetIndexInstance() *IndexInst {
	if m != nil {
		return m.IndexInstance
	}
	return nil
}

// List of instances
type Instances struct {
	Instances            []*Instance `protobuf:"bytes,1,rep,name=instances" json:"instances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Instances) Reset()         { *m = Instances{} }
func (m *Instances) String() string { return proto.CompactTextString(m) }
func (*Instances) ProtoMessage()    {}
func (*Instances) Descriptor() ([]byte, []int) {
	return fileDescriptor_9070c380e1cf3cdd, []int{16}
}

func (m *Instances) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instances.Unmarshal(m, b)
}
func (m *Instances) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instances.Marshal(b, m, deterministic)
}
func (m *Instances) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instances.Merge(m, src)
}
func (m *Instances) XXX_Size() int {
	return xxx_messageInfo_Instances.Size(m)
}
func (m *Instances) XXX_DiscardUnknown() {
	xxx_messageInfo_Instances.DiscardUnknown(m)
}

var xxx_messageInfo_Instances proto.InternalMessageInfo

func (m *Instances) GetInstances() []*Instance {
	if m != nil {
		return m.Instances
	}
	return nil
}

func init() {
	proto.RegisterEnum("protobuf.FeedVersion", FeedVersion_name, FeedVersion_value)
	proto.RegisterType((*VbmapRequest)(nil), "protobuf.VbmapRequest")
	proto.RegisterType((*VbmapResponse)(nil), "protobuf.VbmapResponse")
	proto.RegisterType((*FailoverLogRequest)(nil), "protobuf.FailoverLogRequest")
	proto.RegisterType((*FailoverLogResponse)(nil), "protobuf.FailoverLogResponse")
	proto.RegisterType((*MutationTopicRequest)(nil), "protobuf.MutationTopicRequest")
	proto.RegisterType((*TopicResponse)(nil), "protobuf.TopicResponse")
	proto.RegisterType((*TimestampResponse)(nil), "protobuf.TimestampResponse")
	proto.RegisterType((*RestartVbucketsRequest)(nil), "protobuf.RestartVbucketsRequest")
	proto.RegisterType((*ShutdownVbucketsRequest)(nil), "protobuf.ShutdownVbucketsRequest")
	proto.RegisterType((*AddBucketsRequest)(nil), "protobuf.AddBucketsRequest")
	proto.RegisterType((*DelBucketsRequest)(nil), "protobuf.DelBucketsRequest")
	proto.RegisterType((*AddInstancesRequest)(nil), "protobuf.AddInstancesRequest")
	proto.RegisterType((*DelInstancesRequest)(nil), "protobuf.DelInstancesRequest")
	proto.RegisterType((*RepairEndpointsRequest)(nil), "protobuf.RepairEndpointsRequest")
	proto.RegisterType((*ShutdownTopicRequest)(nil), "protobuf.ShutdownTopicRequest")
	proto.RegisterType((*Instance)(nil), "protobuf.Instance")
	proto.RegisterType((*Instances)(nil), "protobuf.Instances")
}

func init() { proto.RegisterFile("projector.proto", fileDescriptor_9070c380e1cf3cdd) }

var fileDescriptor_9070c380e1cf3cdd = []byte{
	// 663 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcb, 0x6e, 0xdb, 0x38,
	0x14, 0x85, 0x1e, 0x7e, 0xe8, 0xca, 0x8a, 0x23, 0x3a, 0x33, 0x23, 0x04, 0xb3, 0x10, 0x14, 0x04,
	0xa3, 0x09, 0x1a, 0xa3, 0x70, 0x81, 0x02, 0x0d, 0xd0, 0x45, 0x8a, 0xa4, 0x40, 0x80, 0x76, 0x93,
	0x1a, 0x46, 0xb6, 0xb2, 0xc8, 0x3a, 0xaa, 0x65, 0x52, 0x21, 0x29, 0xa7, 0x59, 0xf4, 0xbb, 0xfa,
	0x37, 0xed, 0xaf, 0x14, 0x7a, 0x39, 0x72, 0x6b, 0x25, 0x5a, 0x19, 0x24, 0x0f, 0xef, 0x3d, 0xe7,
	0xdc, 0x23, 0x1a, 0x86, 0x09, 0x67, 0x5f, 0x48, 0x28, 0x19, 0x1f, 0x27, 0x9c, 0x49, 0x86, 0xfa,
	0xf9, 0xcf, 0x3c, 0xfd, 0x7c, 0x38, 0x08, 0xd9, 0x6a, 0xc5, 0x68, 0xb1, 0x7f, 0x68, 0x46, 0x14,
	0x93, 0xaf, 0xc5, 0xc2, 0x7b, 0x0b, 0x83, 0xd9, 0x7c, 0x15, 0x24, 0xd7, 0xe4, 0x2e, 0x25, 0x42,
	0xa2, 0x01, 0xe8, 0x09, 0x63, 0xb1, 0xa3, 0xb8, 0xaa, 0x6f, 0xa0, 0x3d, 0xe8, 0xce, 0xd3, 0x70,
	0x49, 0xa4, 0xa3, 0xe6, 0xeb, 0x21, 0xf4, 0x96, 0xeb, 0x00, 0x63, 0x2e, 0x1c, 0xcd, 0xd5, 0x7c,
	0xc3, 0x0b, 0xc1, 0x2a, 0xaf, 0x8b, 0x84, 0x51, 0x41, 0xea, 0x08, 0x25, 0x43, 0xa0, 0xa3, 0x6c,
	0x63, 0x3d, 0xa7, 0x4c, 0x38, 0xaa, 0xab, 0xf9, 0xe6, 0x04, 0x8d, 0x2b, 0x5e, 0xe3, 0x59, 0x51,
	0x5c, 0xa0, 0x7f, 0x41, 0x23, 0x9c, 0x3b, 0x9a, 0xab, 0xf8, 0xe6, 0x64, 0xf8, 0x08, 0xb8, 0xe4,
	0x9c, 0x71, 0xef, 0x1c, 0xd0, 0xfb, 0x20, 0x8a, 0xd9, 0x9a, 0xf0, 0x0f, 0x6c, 0xd1, 0x8e, 0xa9,
	0x05, 0x9d, 0xa2, 0x69, 0xc6, 0xd3, 0xf2, 0x6e, 0x60, 0xb4, 0x55, 0xa2, 0x64, 0x7b, 0x04, 0x7a,
	0xcc, 0x16, 0x05, 0x55, 0x73, 0xf2, 0xd7, 0x63, 0xe3, 0x1a, 0xb8, 0x22, 0xa7, 0xee, 0x26, 0xf7,
	0x53, 0x81, 0x83, 0x8f, 0xa9, 0x0c, 0x64, 0xc4, 0xe8, 0x94, 0x25, 0x51, 0x58, 0xf1, 0xb3, 0xa0,
	0x23, 0xb3, 0x75, 0x49, 0xf0, 0x00, 0x06, 0x84, 0xe2, 0x84, 0x45, 0x54, 0x4e, 0x1f, 0x12, 0x52,
	0xd2, 0xfc, 0x1f, 0x2c, 0x4e, 0xee, 0xa6, 0xd1, 0x8a, 0x08, 0x19, 0xac, 0x92, 0x82, 0xee, 0x96,
	0x47, 0x53, 0x31, 0x9b, 0xa7, 0x69, 0x84, 0xd1, 0x31, 0x18, 0x11, 0x15, 0x32, 0xa0, 0x21, 0x11,
	0x8e, 0xfe, 0x3b, 0xec, 0xaa, 0x3c, 0x42, 0x2f, 0xa1, 0xb7, 0x26, 0x5c, 0x44, 0x8c, 0x3a, 0x1d,
	0x57, 0xf1, 0xf7, 0xb6, 0x54, 0x11, 0x82, 0x67, 0xc5, 0xe1, 0x59, 0x5f, 0xdc, 0x12, 0x1e, 0xb3,
	0x70, 0x99, 0x11, 0x0d, 0xc4, 0x03, 0x0d, 0x9d, 0xae, 0xab, 0xf8, 0xfd, 0x6c, 0x82, 0x2c, 0x09,
	0xee, 0x52, 0x32, 0x71, 0x7a, 0xae, 0xe2, 0xeb, 0xde, 0x0f, 0x05, 0xac, 0x52, 0x59, 0x69, 0x5b,
	0x4d, 0x9a, 0xe2, 0x1b, 0x68, 0x04, 0x66, 0xc5, 0xec, 0x0a, 0x17, 0x63, 0xd6, 0xd1, 0x0b, 0xd8,
	0x0f, 0x42, 0x19, 0xad, 0x49, 0x2b, 0x71, 0x63, 0x40, 0x9c, 0xc5, 0xf1, 0x3c, 0x08, 0x97, 0x35,
	0xbc, 0xde, 0x88, 0x2f, 0x67, 0xd2, 0xd9, 0x39, 0x13, 0x74, 0x0a, 0x76, 0x42, 0x28, 0x8e, 0xe8,
	0xa2, 0x56, 0xac, 0xdb, 0x54, 0xcc, 0x63, 0x60, 0x6f, 0x70, 0xbb, 0x34, 0x66, 0x83, 0x3a, 0x05,
	0x3b, 0x4c, 0x39, 0x27, 0x54, 0xd6, 0x4a, 0xaa, 0xcf, 0xf1, 0x6b, 0x08, 0xf4, 0x02, 0xfe, 0xbe,
	0xce, 0x6a, 0x70, 0x59, 0x7d, 0x01, 0x0d, 0xa1, 0x39, 0x05, 0x9b, 0x17, 0xc0, 0x56, 0x5d, 0x6b,
	0xa3, 0xd3, 0xf2, 0xd1, 0xdd, 0xc0, 0x3f, 0x9f, 0x6e, 0x53, 0x89, 0xd9, 0x3d, 0x7d, 0xa6, 0xd3,
	0x18, 0x90, 0x28, 0x91, 0x6d, 0x5a, 0x79, 0xdf, 0x15, 0xb0, 0xcf, 0x31, 0x7e, 0xf7, 0x64, 0xd1,
	0x3f, 0xd2, 0xad, 0xb6, 0x4b, 0xb7, 0xd6, 0x26, 0xdd, 0x7a, 0xbb, 0x74, 0xd7, 0x3c, 0xe9, 0xe4,
	0x9e, 0xbc, 0x02, 0xfb, 0x82, 0xc4, 0x4f, 0x13, 0x1f, 0x42, 0xaf, 0xb4, 0x2b, 0xa7, 0x6c, 0x78,
	0xdf, 0x60, 0x74, 0x8e, 0x71, 0x45, 0xa3, 0xe9, 0xda, 0x96, 0x08, 0xb5, 0x8d, 0x08, 0xad, 0x95,
	0x08, 0xef, 0x0d, 0x8c, 0x2e, 0x48, 0xfc, 0x5c, 0xfb, 0x5d, 0xdf, 0xa1, 0x77, 0x96, 0x65, 0x2d,
	0x09, 0x22, 0x7e, 0x59, 0xbe, 0x3e, 0x4d, 0xb7, 0x6d, 0x30, 0xaa, 0x07, 0xaa, 0x52, 0x7d, 0x0c,
	0x07, 0x55, 0x7c, 0x9e, 0x78, 0xda, 0xbc, 0xd7, 0xd0, 0xdf, 0x68, 0x3b, 0x01, 0x2b, 0xff, 0x7b,
	0xa9, 0x36, 0xf2, 0x27, 0xc2, 0x9c, 0x8c, 0xea, 0x36, 0x94, 0xc7, 0xde, 0x04, 0x8c, 0x8d, 0xa4,
	0x6d, 0xef, 0x94, 0x26, 0xef, 0x4e, 0xfe, 0x03, 0xb3, 0x66, 0x11, 0x1a, 0xc0, 0xc6, 0xa4, 0x7d,
	0x05, 0x01, 0x74, 0xef, 0x03, 0x29, 0x18, 0xdd, 0x57, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0xaf,
	0x32, 0x11, 0x34, 0x0f, 0x07, 0x00, 0x00,
}
