// Code generated by protoc-gen-go.
// source: ddl.proto
// DO NOT EDIT!

package protobuf

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// Requested by admin console to create a new index.
type CreateIndexRequest struct {
	Index            *IndexDefn `protobuf:"bytes,1,req,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *CreateIndexRequest) Reset()         { *m = CreateIndexRequest{} }
func (m *CreateIndexRequest) String() string { return proto.CompactTextString(m) }
func (*CreateIndexRequest) ProtoMessage()    {}

func (m *CreateIndexRequest) GetIndex() *IndexDefn {
	if m != nil {
		return m.Index
	}
	return nil
}

type CreateIndexResponse struct {
	IndexUuid        *uint64 `protobuf:"varint,1,req,name=indexUuid" json:"indexUuid,omitempty"`
	Err              *Error  `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateIndexResponse) Reset()         { *m = CreateIndexResponse{} }
func (m *CreateIndexResponse) String() string { return proto.CompactTextString(m) }
func (*CreateIndexResponse) ProtoMessage()    {}

func (m *CreateIndexResponse) GetIndexUuid() uint64 {
	if m != nil && m.IndexUuid != nil {
		return *m.IndexUuid
	}
	return 0
}

func (m *CreateIndexResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

// Requested by admin console for list of all indexes.
type IndexesRequest struct {
	IndexUuids       []uint64 `protobuf:"varint,1,rep,name=indexUuids" json:"indexUuids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *IndexesRequest) Reset()         { *m = IndexesRequest{} }
func (m *IndexesRequest) String() string { return proto.CompactTextString(m) }
func (*IndexesRequest) ProtoMessage()    {}

func (m *IndexesRequest) GetIndexUuids() []uint64 {
	if m != nil {
		return m.IndexUuids
	}
	return nil
}

type IndexesResponse struct {
	Instances        []*IndexInst `protobuf:"bytes,1,rep,name=instances" json:"instances,omitempty"`
	Err              *Error       `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *IndexesResponse) Reset()         { *m = IndexesResponse{} }
func (m *IndexesResponse) String() string { return proto.CompactTextString(m) }
func (*IndexesResponse) ProtoMessage()    {}

func (m *IndexesResponse) GetInstances() []*IndexInst {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *IndexesResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

// Requested by admin console to delete an index. Error message will be sent
// as response.
type DeleteIndexRequest struct {
	IndexUuids       []uint64 `protobuf:"varint,1,rep,name=indexUuids" json:"indexUuids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DeleteIndexRequest) Reset()         { *m = DeleteIndexRequest{} }
func (m *DeleteIndexRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteIndexRequest) ProtoMessage()    {}

func (m *DeleteIndexRequest) GetIndexUuids() []uint64 {
	if m != nil {
		return m.IndexUuids
	}
	return nil
}

// Requested by admin console to start "initial index load" for a set of
// created index. Error message will be sent as response.
type InitialIndexLoadRequest struct {
	IndexUuids       []uint64 `protobuf:"varint,1,rep,name=indexUuids" json:"indexUuids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *InitialIndexLoadRequest) Reset()         { *m = InitialIndexLoadRequest{} }
func (m *InitialIndexLoadRequest) String() string { return proto.CompactTextString(m) }
func (*InitialIndexLoadRequest) ProtoMessage()    {}

func (m *InitialIndexLoadRequest) GetIndexUuids() []uint64 {
	if m != nil {
		return m.IndexUuids
	}
	return nil
}

func init() {
}
