// Code generated by protoc-gen-go. DO NOT EDIT.
// source: query.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Error message can be sent back as response or
// encapsulated in response packets.
type Error struct {
	Error                *string  `protobuf:"bytes,1,req,name=error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

// consistency timestamp specifying a subset of vbucket.
// AnyConsistency, this message is typically ignored.
// SessionConsistency, {vbnos, seqnos, crc64} are to be considered.
// QueryConsistency, {vbnos, seqnos, vbuuids} are to be considered.
type TsConsistency struct {
	Vbnos                []uint32 `protobuf:"varint,1,rep,name=vbnos" json:"vbnos,omitempty"`
	Seqnos               []uint64 `protobuf:"varint,2,rep,name=seqnos" json:"seqnos,omitempty"`
	Vbuuids              []uint64 `protobuf:"varint,3,rep,name=vbuuids" json:"vbuuids,omitempty"`
	Crc64                *uint64  `protobuf:"varint,4,opt,name=crc64" json:"crc64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TsConsistency) Reset()         { *m = TsConsistency{} }
func (m *TsConsistency) String() string { return proto.CompactTextString(m) }
func (*TsConsistency) ProtoMessage()    {}
func (*TsConsistency) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{1}
}

func (m *TsConsistency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TsConsistency.Unmarshal(m, b)
}
func (m *TsConsistency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TsConsistency.Marshal(b, m, deterministic)
}
func (m *TsConsistency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TsConsistency.Merge(m, src)
}
func (m *TsConsistency) XXX_Size() int {
	return xxx_messageInfo_TsConsistency.Size(m)
}
func (m *TsConsistency) XXX_DiscardUnknown() {
	xxx_messageInfo_TsConsistency.DiscardUnknown(m)
}

var xxx_messageInfo_TsConsistency proto.InternalMessageInfo

func (m *TsConsistency) GetVbnos() []uint32 {
	if m != nil {
		return m.Vbnos
	}
	return nil
}

func (m *TsConsistency) GetSeqnos() []uint64 {
	if m != nil {
		return m.Seqnos
	}
	return nil
}

func (m *TsConsistency) GetVbuuids() []uint64 {
	if m != nil {
		return m.Vbuuids
	}
	return nil
}

func (m *TsConsistency) GetCrc64() uint64 {
	if m != nil && m.Crc64 != nil {
		return *m.Crc64
	}
	return 0
}

// Request can be one of the optional field.
type QueryPayload struct {
	Version              *uint32             `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	StatisticsRequest    *StatisticsRequest  `protobuf:"bytes,2,opt,name=statisticsRequest" json:"statisticsRequest,omitempty"`
	Statistics           *StatisticsResponse `protobuf:"bytes,3,opt,name=statistics" json:"statistics,omitempty"`
	ScanRequest          *ScanRequest        `protobuf:"bytes,4,opt,name=scanRequest" json:"scanRequest,omitempty"`
	ScanAllRequest       *ScanAllRequest     `protobuf:"bytes,5,opt,name=scanAllRequest" json:"scanAllRequest,omitempty"`
	Stream               *ResponseStream     `protobuf:"bytes,6,opt,name=stream" json:"stream,omitempty"`
	CountRequest         *CountRequest       `protobuf:"bytes,7,opt,name=countRequest" json:"countRequest,omitempty"`
	CountResponse        *CountResponse      `protobuf:"bytes,8,opt,name=countResponse" json:"countResponse,omitempty"`
	EndStream            *EndStreamRequest   `protobuf:"bytes,9,opt,name=endStream" json:"endStream,omitempty"`
	StreamEnd            *StreamEndResponse  `protobuf:"bytes,10,opt,name=streamEnd" json:"streamEnd,omitempty"`
	HeloRequest          *HeloRequest        `protobuf:"bytes,11,opt,name=heloRequest" json:"heloRequest,omitempty"`
	HeloResponse         *HeloResponse       `protobuf:"bytes,12,opt,name=heloResponse" json:"heloResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryPayload) Reset()         { *m = QueryPayload{} }
func (m *QueryPayload) String() string { return proto.CompactTextString(m) }
func (*QueryPayload) ProtoMessage()    {}
func (*QueryPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{2}
}

func (m *QueryPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPayload.Unmarshal(m, b)
}
func (m *QueryPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPayload.Marshal(b, m, deterministic)
}
func (m *QueryPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPayload.Merge(m, src)
}
func (m *QueryPayload) XXX_Size() int {
	return xxx_messageInfo_QueryPayload.Size(m)
}
func (m *QueryPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPayload.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPayload proto.InternalMessageInfo

func (m *QueryPayload) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *QueryPayload) GetStatisticsRequest() *StatisticsRequest {
	if m != nil {
		return m.StatisticsRequest
	}
	return nil
}

func (m *QueryPayload) GetStatistics() *StatisticsResponse {
	if m != nil {
		return m.Statistics
	}
	return nil
}

func (m *QueryPayload) GetScanRequest() *ScanRequest {
	if m != nil {
		return m.ScanRequest
	}
	return nil
}

func (m *QueryPayload) GetScanAllRequest() *ScanAllRequest {
	if m != nil {
		return m.ScanAllRequest
	}
	return nil
}

func (m *QueryPayload) GetStream() *ResponseStream {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (m *QueryPayload) GetCountRequest() *CountRequest {
	if m != nil {
		return m.CountRequest
	}
	return nil
}

func (m *QueryPayload) GetCountResponse() *CountResponse {
	if m != nil {
		return m.CountResponse
	}
	return nil
}

func (m *QueryPayload) GetEndStream() *EndStreamRequest {
	if m != nil {
		return m.EndStream
	}
	return nil
}

func (m *QueryPayload) GetStreamEnd() *StreamEndResponse {
	if m != nil {
		return m.StreamEnd
	}
	return nil
}

func (m *QueryPayload) GetHeloRequest() *HeloRequest {
	if m != nil {
		return m.HeloRequest
	}
	return nil
}

func (m *QueryPayload) GetHeloResponse() *HeloResponse {
	if m != nil {
		return m.HeloResponse
	}
	return nil
}

// Get current server version/capabilities
type HeloRequest struct {
	Version              *uint32  `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeloRequest) Reset()         { *m = HeloRequest{} }
func (m *HeloRequest) String() string { return proto.CompactTextString(m) }
func (*HeloRequest) ProtoMessage()    {}
func (*HeloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{3}
}

func (m *HeloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeloRequest.Unmarshal(m, b)
}
func (m *HeloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeloRequest.Marshal(b, m, deterministic)
}
func (m *HeloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeloRequest.Merge(m, src)
}
func (m *HeloRequest) XXX_Size() int {
	return xxx_messageInfo_HeloRequest.Size(m)
}
func (m *HeloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeloRequest proto.InternalMessageInfo

func (m *HeloRequest) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type HeloResponse struct {
	Version              *uint32  `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeloResponse) Reset()         { *m = HeloResponse{} }
func (m *HeloResponse) String() string { return proto.CompactTextString(m) }
func (*HeloResponse) ProtoMessage()    {}
func (*HeloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{4}
}

func (m *HeloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeloResponse.Unmarshal(m, b)
}
func (m *HeloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeloResponse.Marshal(b, m, deterministic)
}
func (m *HeloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeloResponse.Merge(m, src)
}
func (m *HeloResponse) XXX_Size() int {
	return xxx_messageInfo_HeloResponse.Size(m)
}
func (m *HeloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeloResponse proto.InternalMessageInfo

func (m *HeloResponse) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

// Get Index statistics. StatisticsResponse is returned back from indexer.
type StatisticsRequest struct {
	DefnID               *uint64  `protobuf:"varint,1,req,name=defnID" json:"defnID,omitempty"`
	Span                 *Span    `protobuf:"bytes,2,req,name=span" json:"span,omitempty"`
	RequestId            *string  `protobuf:"bytes,3,opt,name=requestId" json:"requestId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatisticsRequest) Reset()         { *m = StatisticsRequest{} }
func (m *StatisticsRequest) String() string { return proto.CompactTextString(m) }
func (*StatisticsRequest) ProtoMessage()    {}
func (*StatisticsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{5}
}

func (m *StatisticsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatisticsRequest.Unmarshal(m, b)
}
func (m *StatisticsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatisticsRequest.Marshal(b, m, deterministic)
}
func (m *StatisticsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatisticsRequest.Merge(m, src)
}
func (m *StatisticsRequest) XXX_Size() int {
	return xxx_messageInfo_StatisticsRequest.Size(m)
}
func (m *StatisticsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatisticsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatisticsRequest proto.InternalMessageInfo

func (m *StatisticsRequest) GetDefnID() uint64 {
	if m != nil && m.DefnID != nil {
		return *m.DefnID
	}
	return 0
}

func (m *StatisticsRequest) GetSpan() *Span {
	if m != nil {
		return m.Span
	}
	return nil
}

func (m *StatisticsRequest) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

type StatisticsResponse struct {
	Stats                *IndexStatistics `protobuf:"bytes,1,req,name=stats" json:"stats,omitempty"`
	Err                  *Error           `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StatisticsResponse) Reset()         { *m = StatisticsResponse{} }
func (m *StatisticsResponse) String() string { return proto.CompactTextString(m) }
func (*StatisticsResponse) ProtoMessage()    {}
func (*StatisticsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{6}
}

func (m *StatisticsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatisticsResponse.Unmarshal(m, b)
}
func (m *StatisticsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatisticsResponse.Marshal(b, m, deterministic)
}
func (m *StatisticsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatisticsResponse.Merge(m, src)
}
func (m *StatisticsResponse) XXX_Size() int {
	return xxx_messageInfo_StatisticsResponse.Size(m)
}
func (m *StatisticsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatisticsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatisticsResponse proto.InternalMessageInfo

func (m *StatisticsResponse) GetStats() *IndexStatistics {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *StatisticsResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

// Scan request to indexer.
type ScanRequest struct {
	DefnID               *uint64          `protobuf:"varint,1,req,name=defnID" json:"defnID,omitempty"`
	Span                 *Span            `protobuf:"bytes,2,req,name=span" json:"span,omitempty"`
	Distinct             *bool            `protobuf:"varint,3,req,name=distinct" json:"distinct,omitempty"`
	Limit                *int64           `protobuf:"varint,4,req,name=limit" json:"limit,omitempty"`
	Cons                 *uint32          `protobuf:"varint,5,req,name=cons" json:"cons,omitempty"`
	Vector               *TsConsistency   `protobuf:"bytes,6,opt,name=vector" json:"vector,omitempty"`
	RequestId            *string          `protobuf:"bytes,7,opt,name=requestId" json:"requestId,omitempty"`
	Scans                []*Scan          `protobuf:"bytes,8,rep,name=scans" json:"scans,omitempty"`
	Indexprojection      *IndexProjection `protobuf:"bytes,9,opt,name=indexprojection" json:"indexprojection,omitempty"`
	Reverse              *bool            `protobuf:"varint,10,opt,name=reverse" json:"reverse,omitempty"`
	Offset               *int64           `protobuf:"varint,11,opt,name=offset" json:"offset,omitempty"`
	RollbackTime         *int64           `protobuf:"varint,12,opt,name=rollbackTime" json:"rollbackTime,omitempty"`
	PartitionIds         []uint64         `protobuf:"varint,13,rep,name=partitionIds" json:"partitionIds,omitempty"`
	GroupAggr            *GroupAggr       `protobuf:"bytes,14,opt,name=groupAggr" json:"groupAggr,omitempty"`
	Sorted               *bool            `protobuf:"varint,15,opt,name=sorted" json:"sorted,omitempty"`
	DataEncFmt           *uint32          `protobuf:"varint,16,opt,name=dataEncFmt" json:"dataEncFmt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ScanRequest) Reset()         { *m = ScanRequest{} }
func (m *ScanRequest) String() string { return proto.CompactTextString(m) }
func (*ScanRequest) ProtoMessage()    {}
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{7}
}

func (m *ScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanRequest.Unmarshal(m, b)
}
func (m *ScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanRequest.Marshal(b, m, deterministic)
}
func (m *ScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanRequest.Merge(m, src)
}
func (m *ScanRequest) XXX_Size() int {
	return xxx_messageInfo_ScanRequest.Size(m)
}
func (m *ScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanRequest proto.InternalMessageInfo

func (m *ScanRequest) GetDefnID() uint64 {
	if m != nil && m.DefnID != nil {
		return *m.DefnID
	}
	return 0
}

func (m *ScanRequest) GetSpan() *Span {
	if m != nil {
		return m.Span
	}
	return nil
}

func (m *ScanRequest) GetDistinct() bool {
	if m != nil && m.Distinct != nil {
		return *m.Distinct
	}
	return false
}

func (m *ScanRequest) GetLimit() int64 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

func (m *ScanRequest) GetCons() uint32 {
	if m != nil && m.Cons != nil {
		return *m.Cons
	}
	return 0
}

func (m *ScanRequest) GetVector() *TsConsistency {
	if m != nil {
		return m.Vector
	}
	return nil
}

func (m *ScanRequest) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *ScanRequest) GetScans() []*Scan {
	if m != nil {
		return m.Scans
	}
	return nil
}

func (m *ScanRequest) GetIndexprojection() *IndexProjection {
	if m != nil {
		return m.Indexprojection
	}
	return nil
}

func (m *ScanRequest) GetReverse() bool {
	if m != nil && m.Reverse != nil {
		return *m.Reverse
	}
	return false
}

func (m *ScanRequest) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *ScanRequest) GetRollbackTime() int64 {
	if m != nil && m.RollbackTime != nil {
		return *m.RollbackTime
	}
	return 0
}

func (m *ScanRequest) GetPartitionIds() []uint64 {
	if m != nil {
		return m.PartitionIds
	}
	return nil
}

func (m *ScanRequest) GetGroupAggr() *GroupAggr {
	if m != nil {
		return m.GroupAggr
	}
	return nil
}

func (m *ScanRequest) GetSorted() bool {
	if m != nil && m.Sorted != nil {
		return *m.Sorted
	}
	return false
}

func (m *ScanRequest) GetDataEncFmt() uint32 {
	if m != nil && m.DataEncFmt != nil {
		return *m.DataEncFmt
	}
	return 0
}

// Full table scan request from indexer.
type ScanAllRequest struct {
	DefnID               *uint64        `protobuf:"varint,1,req,name=defnID" json:"defnID,omitempty"`
	Limit                *int64         `protobuf:"varint,2,req,name=limit" json:"limit,omitempty"`
	Cons                 *uint32        `protobuf:"varint,3,req,name=cons" json:"cons,omitempty"`
	Vector               *TsConsistency `protobuf:"bytes,4,opt,name=vector" json:"vector,omitempty"`
	RequestId            *string        `protobuf:"bytes,5,opt,name=requestId" json:"requestId,omitempty"`
	RollbackTime         *int64         `protobuf:"varint,6,opt,name=rollbackTime" json:"rollbackTime,omitempty"`
	PartitionIds         []uint64       `protobuf:"varint,7,rep,name=partitionIds" json:"partitionIds,omitempty"`
	DataEncFmt           *uint32        `protobuf:"varint,8,opt,name=dataEncFmt" json:"dataEncFmt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ScanAllRequest) Reset()         { *m = ScanAllRequest{} }
func (m *ScanAllRequest) String() string { return proto.CompactTextString(m) }
func (*ScanAllRequest) ProtoMessage()    {}
func (*ScanAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{8}
}

func (m *ScanAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanAllRequest.Unmarshal(m, b)
}
func (m *ScanAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanAllRequest.Marshal(b, m, deterministic)
}
func (m *ScanAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanAllRequest.Merge(m, src)
}
func (m *ScanAllRequest) XXX_Size() int {
	return xxx_messageInfo_ScanAllRequest.Size(m)
}
func (m *ScanAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanAllRequest proto.InternalMessageInfo

func (m *ScanAllRequest) GetDefnID() uint64 {
	if m != nil && m.DefnID != nil {
		return *m.DefnID
	}
	return 0
}

func (m *ScanAllRequest) GetLimit() int64 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

func (m *ScanAllRequest) GetCons() uint32 {
	if m != nil && m.Cons != nil {
		return *m.Cons
	}
	return 0
}

func (m *ScanAllRequest) GetVector() *TsConsistency {
	if m != nil {
		return m.Vector
	}
	return nil
}

func (m *ScanAllRequest) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *ScanAllRequest) GetRollbackTime() int64 {
	if m != nil && m.RollbackTime != nil {
		return *m.RollbackTime
	}
	return 0
}

func (m *ScanAllRequest) GetPartitionIds() []uint64 {
	if m != nil {
		return m.PartitionIds
	}
	return nil
}

func (m *ScanAllRequest) GetDataEncFmt() uint32 {
	if m != nil && m.DataEncFmt != nil {
		return *m.DataEncFmt
	}
	return 0
}

// Request by client to stop streaming the query results.
type EndStreamRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndStreamRequest) Reset()         { *m = EndStreamRequest{} }
func (m *EndStreamRequest) String() string { return proto.CompactTextString(m) }
func (*EndStreamRequest) ProtoMessage()    {}
func (*EndStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{9}
}

func (m *EndStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndStreamRequest.Unmarshal(m, b)
}
func (m *EndStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndStreamRequest.Marshal(b, m, deterministic)
}
func (m *EndStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndStreamRequest.Merge(m, src)
}
func (m *EndStreamRequest) XXX_Size() int {
	return xxx_messageInfo_EndStreamRequest.Size(m)
}
func (m *EndStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndStreamRequest proto.InternalMessageInfo

type ResponseStream struct {
	IndexEntries         []*IndexEntry `protobuf:"bytes,1,rep,name=indexEntries" json:"indexEntries,omitempty"`
	Err                  *Error        `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ResponseStream) Reset()         { *m = ResponseStream{} }
func (m *ResponseStream) String() string { return proto.CompactTextString(m) }
func (*ResponseStream) ProtoMessage()    {}
func (*ResponseStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{10}
}

func (m *ResponseStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStream.Unmarshal(m, b)
}
func (m *ResponseStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStream.Marshal(b, m, deterministic)
}
func (m *ResponseStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStream.Merge(m, src)
}
func (m *ResponseStream) XXX_Size() int {
	return xxx_messageInfo_ResponseStream.Size(m)
}
func (m *ResponseStream) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStream.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStream proto.InternalMessageInfo

func (m *ResponseStream) GetIndexEntries() []*IndexEntry {
	if m != nil {
		return m.IndexEntries
	}
	return nil
}

func (m *ResponseStream) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

// Last response packet sent by server to end query results.
type StreamEndResponse struct {
	Err                  *Error   `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamEndResponse) Reset()         { *m = StreamEndResponse{} }
func (m *StreamEndResponse) String() string { return proto.CompactTextString(m) }
func (*StreamEndResponse) ProtoMessage()    {}
func (*StreamEndResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{11}
}

func (m *StreamEndResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamEndResponse.Unmarshal(m, b)
}
func (m *StreamEndResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamEndResponse.Marshal(b, m, deterministic)
}
func (m *StreamEndResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamEndResponse.Merge(m, src)
}
func (m *StreamEndResponse) XXX_Size() int {
	return xxx_messageInfo_StreamEndResponse.Size(m)
}
func (m *StreamEndResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamEndResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamEndResponse proto.InternalMessageInfo

func (m *StreamEndResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

// Count request to indexer.
type CountRequest struct {
	DefnID               *uint64        `protobuf:"varint,1,req,name=defnID" json:"defnID,omitempty"`
	Span                 *Span          `protobuf:"bytes,2,req,name=span" json:"span,omitempty"`
	Cons                 *uint32        `protobuf:"varint,3,req,name=cons" json:"cons,omitempty"`
	Vector               *TsConsistency `protobuf:"bytes,4,opt,name=vector" json:"vector,omitempty"`
	RequestId            *string        `protobuf:"bytes,5,opt,name=requestId" json:"requestId,omitempty"`
	Distinct             *bool          `protobuf:"varint,6,opt,name=distinct" json:"distinct,omitempty"`
	Scans                []*Scan        `protobuf:"bytes,7,rep,name=scans" json:"scans,omitempty"`
	RollbackTime         *int64         `protobuf:"varint,8,opt,name=rollbackTime" json:"rollbackTime,omitempty"`
	PartitionIds         []uint64       `protobuf:"varint,9,rep,name=partitionIds" json:"partitionIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CountRequest) Reset()         { *m = CountRequest{} }
func (m *CountRequest) String() string { return proto.CompactTextString(m) }
func (*CountRequest) ProtoMessage()    {}
func (*CountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{12}
}

func (m *CountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountRequest.Unmarshal(m, b)
}
func (m *CountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountRequest.Marshal(b, m, deterministic)
}
func (m *CountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountRequest.Merge(m, src)
}
func (m *CountRequest) XXX_Size() int {
	return xxx_messageInfo_CountRequest.Size(m)
}
func (m *CountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CountRequest proto.InternalMessageInfo

func (m *CountRequest) GetDefnID() uint64 {
	if m != nil && m.DefnID != nil {
		return *m.DefnID
	}
	return 0
}

func (m *CountRequest) GetSpan() *Span {
	if m != nil {
		return m.Span
	}
	return nil
}

func (m *CountRequest) GetCons() uint32 {
	if m != nil && m.Cons != nil {
		return *m.Cons
	}
	return 0
}

func (m *CountRequest) GetVector() *TsConsistency {
	if m != nil {
		return m.Vector
	}
	return nil
}

func (m *CountRequest) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *CountRequest) GetDistinct() bool {
	if m != nil && m.Distinct != nil {
		return *m.Distinct
	}
	return false
}

func (m *CountRequest) GetScans() []*Scan {
	if m != nil {
		return m.Scans
	}
	return nil
}

func (m *CountRequest) GetRollbackTime() int64 {
	if m != nil && m.RollbackTime != nil {
		return *m.RollbackTime
	}
	return 0
}

func (m *CountRequest) GetPartitionIds() []uint64 {
	if m != nil {
		return m.PartitionIds
	}
	return nil
}

// total number of entries in index.
type CountResponse struct {
	Count                *int64   `protobuf:"varint,1,req,name=count" json:"count,omitempty"`
	Err                  *Error   `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountResponse) Reset()         { *m = CountResponse{} }
func (m *CountResponse) String() string { return proto.CompactTextString(m) }
func (*CountResponse) ProtoMessage()    {}
func (*CountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{13}
}

func (m *CountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountResponse.Unmarshal(m, b)
}
func (m *CountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountResponse.Marshal(b, m, deterministic)
}
func (m *CountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountResponse.Merge(m, src)
}
func (m *CountResponse) XXX_Size() int {
	return xxx_messageInfo_CountResponse.Size(m)
}
func (m *CountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountResponse proto.InternalMessageInfo

func (m *CountResponse) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *CountResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type Span struct {
	Range                *Range   `protobuf:"bytes,1,opt,name=range" json:"range,omitempty"`
	Equals               [][]byte `protobuf:"bytes,2,rep,name=equals" json:"equals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Span) Reset()         { *m = Span{} }
func (m *Span) String() string { return proto.CompactTextString(m) }
func (*Span) ProtoMessage()    {}
func (*Span) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{14}
}

func (m *Span) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Span.Unmarshal(m, b)
}
func (m *Span) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Span.Marshal(b, m, deterministic)
}
func (m *Span) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span.Merge(m, src)
}
func (m *Span) XXX_Size() int {
	return xxx_messageInfo_Span.Size(m)
}
func (m *Span) XXX_DiscardUnknown() {
	xxx_messageInfo_Span.DiscardUnknown(m)
}

var xxx_messageInfo_Span proto.InternalMessageInfo

func (m *Span) GetRange() *Range {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *Span) GetEquals() [][]byte {
	if m != nil {
		return m.Equals
	}
	return nil
}

type Range struct {
	Low                  []byte   `protobuf:"bytes,1,opt,name=low" json:"low,omitempty"`
	High                 []byte   `protobuf:"bytes,2,opt,name=high" json:"high,omitempty"`
	Inclusion            *uint32  `protobuf:"varint,3,req,name=inclusion" json:"inclusion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Range) Reset()         { *m = Range{} }
func (m *Range) String() string { return proto.CompactTextString(m) }
func (*Range) ProtoMessage()    {}
func (*Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{15}
}

func (m *Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Range.Unmarshal(m, b)
}
func (m *Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Range.Marshal(b, m, deterministic)
}
func (m *Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Range.Merge(m, src)
}
func (m *Range) XXX_Size() int {
	return xxx_messageInfo_Range.Size(m)
}
func (m *Range) XXX_DiscardUnknown() {
	xxx_messageInfo_Range.DiscardUnknown(m)
}

var xxx_messageInfo_Range proto.InternalMessageInfo

func (m *Range) GetLow() []byte {
	if m != nil {
		return m.Low
	}
	return nil
}

func (m *Range) GetHigh() []byte {
	if m != nil {
		return m.High
	}
	return nil
}

func (m *Range) GetInclusion() uint32 {
	if m != nil && m.Inclusion != nil {
		return *m.Inclusion
	}
	return 0
}

type CompositeElementFilter struct {
	Low                  []byte   `protobuf:"bytes,1,opt,name=low" json:"low,omitempty"`
	High                 []byte   `protobuf:"bytes,2,opt,name=high" json:"high,omitempty"`
	Inclusion            *uint32  `protobuf:"varint,3,req,name=inclusion" json:"inclusion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompositeElementFilter) Reset()         { *m = CompositeElementFilter{} }
func (m *CompositeElementFilter) String() string { return proto.CompactTextString(m) }
func (*CompositeElementFilter) ProtoMessage()    {}
func (*CompositeElementFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{16}
}

func (m *CompositeElementFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompositeElementFilter.Unmarshal(m, b)
}
func (m *CompositeElementFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompositeElementFilter.Marshal(b, m, deterministic)
}
func (m *CompositeElementFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompositeElementFilter.Merge(m, src)
}
func (m *CompositeElementFilter) XXX_Size() int {
	return xxx_messageInfo_CompositeElementFilter.Size(m)
}
func (m *CompositeElementFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_CompositeElementFilter.DiscardUnknown(m)
}

var xxx_messageInfo_CompositeElementFilter proto.InternalMessageInfo

func (m *CompositeElementFilter) GetLow() []byte {
	if m != nil {
		return m.Low
	}
	return nil
}

func (m *CompositeElementFilter) GetHigh() []byte {
	if m != nil {
		return m.High
	}
	return nil
}

func (m *CompositeElementFilter) GetInclusion() uint32 {
	if m != nil && m.Inclusion != nil {
		return *m.Inclusion
	}
	return 0
}

type Scan struct {
	Filters              []*CompositeElementFilter `protobuf:"bytes,1,rep,name=filters" json:"filters,omitempty"`
	Equals               [][]byte                  `protobuf:"bytes,2,rep,name=equals" json:"equals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Scan) Reset()         { *m = Scan{} }
func (m *Scan) String() string { return proto.CompactTextString(m) }
func (*Scan) ProtoMessage()    {}
func (*Scan) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{17}
}

func (m *Scan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scan.Unmarshal(m, b)
}
func (m *Scan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scan.Marshal(b, m, deterministic)
}
func (m *Scan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scan.Merge(m, src)
}
func (m *Scan) XXX_Size() int {
	return xxx_messageInfo_Scan.Size(m)
}
func (m *Scan) XXX_DiscardUnknown() {
	xxx_messageInfo_Scan.DiscardUnknown(m)
}

var xxx_messageInfo_Scan proto.InternalMessageInfo

func (m *Scan) GetFilters() []*CompositeElementFilter {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *Scan) GetEquals() [][]byte {
	if m != nil {
		return m.Equals
	}
	return nil
}

type IndexProjection struct {
	EntryKeys            []int64  `protobuf:"varint,1,rep,name=EntryKeys" json:"EntryKeys,omitempty"`
	PrimaryKey           *bool    `protobuf:"varint,2,opt,name=PrimaryKey" json:"PrimaryKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexProjection) Reset()         { *m = IndexProjection{} }
func (m *IndexProjection) String() string { return proto.CompactTextString(m) }
func (*IndexProjection) ProtoMessage()    {}
func (*IndexProjection) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{18}
}

func (m *IndexProjection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexProjection.Unmarshal(m, b)
}
func (m *IndexProjection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexProjection.Marshal(b, m, deterministic)
}
func (m *IndexProjection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexProjection.Merge(m, src)
}
func (m *IndexProjection) XXX_Size() int {
	return xxx_messageInfo_IndexProjection.Size(m)
}
func (m *IndexProjection) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexProjection.DiscardUnknown(m)
}

var xxx_messageInfo_IndexProjection proto.InternalMessageInfo

func (m *IndexProjection) GetEntryKeys() []int64 {
	if m != nil {
		return m.EntryKeys
	}
	return nil
}

func (m *IndexProjection) GetPrimaryKey() bool {
	if m != nil && m.PrimaryKey != nil {
		return *m.PrimaryKey
	}
	return false
}

type IndexEntry struct {
	EntryKey             []byte   `protobuf:"bytes,1,opt,name=entryKey" json:"entryKey,omitempty"`
	PrimaryKey           []byte   `protobuf:"bytes,2,req,name=primaryKey" json:"primaryKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexEntry) Reset()         { *m = IndexEntry{} }
func (m *IndexEntry) String() string { return proto.CompactTextString(m) }
func (*IndexEntry) ProtoMessage()    {}
func (*IndexEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{19}
}

func (m *IndexEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexEntry.Unmarshal(m, b)
}
func (m *IndexEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexEntry.Marshal(b, m, deterministic)
}
func (m *IndexEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexEntry.Merge(m, src)
}
func (m *IndexEntry) XXX_Size() int {
	return xxx_messageInfo_IndexEntry.Size(m)
}
func (m *IndexEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexEntry.DiscardUnknown(m)
}

var xxx_messageInfo_IndexEntry proto.InternalMessageInfo

func (m *IndexEntry) GetEntryKey() []byte {
	if m != nil {
		return m.EntryKey
	}
	return nil
}

func (m *IndexEntry) GetPrimaryKey() []byte {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

// Statistics of a given index.
type IndexStatistics struct {
	KeysCount            *uint64  `protobuf:"varint,1,req,name=keysCount" json:"keysCount,omitempty"`
	UniqueKeysCount      *uint64  `protobuf:"varint,2,req,name=uniqueKeysCount" json:"uniqueKeysCount,omitempty"`
	KeyMin               []byte   `protobuf:"bytes,3,req,name=keyMin" json:"keyMin,omitempty"`
	KeyMax               []byte   `protobuf:"bytes,4,req,name=keyMax" json:"keyMax,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexStatistics) Reset()         { *m = IndexStatistics{} }
func (m *IndexStatistics) String() string { return proto.CompactTextString(m) }
func (*IndexStatistics) ProtoMessage()    {}
func (*IndexStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{20}
}

func (m *IndexStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexStatistics.Unmarshal(m, b)
}
func (m *IndexStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexStatistics.Marshal(b, m, deterministic)
}
func (m *IndexStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexStatistics.Merge(m, src)
}
func (m *IndexStatistics) XXX_Size() int {
	return xxx_messageInfo_IndexStatistics.Size(m)
}
func (m *IndexStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_IndexStatistics proto.InternalMessageInfo

func (m *IndexStatistics) GetKeysCount() uint64 {
	if m != nil && m.KeysCount != nil {
		return *m.KeysCount
	}
	return 0
}

func (m *IndexStatistics) GetUniqueKeysCount() uint64 {
	if m != nil && m.UniqueKeysCount != nil {
		return *m.UniqueKeysCount
	}
	return 0
}

func (m *IndexStatistics) GetKeyMin() []byte {
	if m != nil {
		return m.KeyMin
	}
	return nil
}

func (m *IndexStatistics) GetKeyMax() []byte {
	if m != nil {
		return m.KeyMax
	}
	return nil
}

type GroupKey struct {
	EntryKeyId           *int32   `protobuf:"varint,1,opt,name=entryKeyId" json:"entryKeyId,omitempty"`
	KeyPos               *int32   `protobuf:"varint,2,req,name=keyPos" json:"keyPos,omitempty"`
	Expr                 []byte   `protobuf:"bytes,3,opt,name=expr" json:"expr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupKey) Reset()         { *m = GroupKey{} }
func (m *GroupKey) String() string { return proto.CompactTextString(m) }
func (*GroupKey) ProtoMessage()    {}
func (*GroupKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{21}
}

func (m *GroupKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupKey.Unmarshal(m, b)
}
func (m *GroupKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupKey.Marshal(b, m, deterministic)
}
func (m *GroupKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupKey.Merge(m, src)
}
func (m *GroupKey) XXX_Size() int {
	return xxx_messageInfo_GroupKey.Size(m)
}
func (m *GroupKey) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupKey.DiscardUnknown(m)
}

var xxx_messageInfo_GroupKey proto.InternalMessageInfo

func (m *GroupKey) GetEntryKeyId() int32 {
	if m != nil && m.EntryKeyId != nil {
		return *m.EntryKeyId
	}
	return 0
}

func (m *GroupKey) GetKeyPos() int32 {
	if m != nil && m.KeyPos != nil {
		return *m.KeyPos
	}
	return 0
}

func (m *GroupKey) GetExpr() []byte {
	if m != nil {
		return m.Expr
	}
	return nil
}

type Aggregate struct {
	AggrFunc             *uint32  `protobuf:"varint,1,req,name=aggrFunc" json:"aggrFunc,omitempty"`
	EntryKeyId           *int32   `protobuf:"varint,2,opt,name=entryKeyId" json:"entryKeyId,omitempty"`
	KeyPos               *int32   `protobuf:"varint,3,req,name=keyPos" json:"keyPos,omitempty"`
	Expr                 []byte   `protobuf:"bytes,4,opt,name=expr" json:"expr,omitempty"`
	Distinct             *bool    `protobuf:"varint,5,opt,name=distinct" json:"distinct,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Aggregate) Reset()         { *m = Aggregate{} }
func (m *Aggregate) String() string { return proto.CompactTextString(m) }
func (*Aggregate) ProtoMessage()    {}
func (*Aggregate) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{22}
}

func (m *Aggregate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Aggregate.Unmarshal(m, b)
}
func (m *Aggregate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Aggregate.Marshal(b, m, deterministic)
}
func (m *Aggregate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Aggregate.Merge(m, src)
}
func (m *Aggregate) XXX_Size() int {
	return xxx_messageInfo_Aggregate.Size(m)
}
func (m *Aggregate) XXX_DiscardUnknown() {
	xxx_messageInfo_Aggregate.DiscardUnknown(m)
}

var xxx_messageInfo_Aggregate proto.InternalMessageInfo

func (m *Aggregate) GetAggrFunc() uint32 {
	if m != nil && m.AggrFunc != nil {
		return *m.AggrFunc
	}
	return 0
}

func (m *Aggregate) GetEntryKeyId() int32 {
	if m != nil && m.EntryKeyId != nil {
		return *m.EntryKeyId
	}
	return 0
}

func (m *Aggregate) GetKeyPos() int32 {
	if m != nil && m.KeyPos != nil {
		return *m.KeyPos
	}
	return 0
}

func (m *Aggregate) GetExpr() []byte {
	if m != nil {
		return m.Expr
	}
	return nil
}

func (m *Aggregate) GetDistinct() bool {
	if m != nil && m.Distinct != nil {
		return *m.Distinct
	}
	return false
}

type GroupAggr struct {
	Name                 []byte       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	GroupKeys            []*GroupKey  `protobuf:"bytes,2,rep,name=groupKeys" json:"groupKeys,omitempty"`
	Aggrs                []*Aggregate `protobuf:"bytes,3,rep,name=aggrs" json:"aggrs,omitempty"`
	DependsOnIndexKeys   []int32      `protobuf:"varint,4,rep,name=dependsOnIndexKeys" json:"dependsOnIndexKeys,omitempty"`
	IndexKeyNames        [][]byte     `protobuf:"bytes,5,rep,name=indexKeyNames" json:"indexKeyNames,omitempty"`
	AllowPartialAggr     *bool        `protobuf:"varint,6,opt,name=allowPartialAggr" json:"allowPartialAggr,omitempty"`
	OnePerPrimaryKey     *bool        `protobuf:"varint,7,opt,name=onePerPrimaryKey" json:"onePerPrimaryKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GroupAggr) Reset()         { *m = GroupAggr{} }
func (m *GroupAggr) String() string { return proto.CompactTextString(m) }
func (*GroupAggr) ProtoMessage()    {}
func (*GroupAggr) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{23}
}

func (m *GroupAggr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupAggr.Unmarshal(m, b)
}
func (m *GroupAggr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupAggr.Marshal(b, m, deterministic)
}
func (m *GroupAggr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupAggr.Merge(m, src)
}
func (m *GroupAggr) XXX_Size() int {
	return xxx_messageInfo_GroupAggr.Size(m)
}
func (m *GroupAggr) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupAggr.DiscardUnknown(m)
}

var xxx_messageInfo_GroupAggr proto.InternalMessageInfo

func (m *GroupAggr) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *GroupAggr) GetGroupKeys() []*GroupKey {
	if m != nil {
		return m.GroupKeys
	}
	return nil
}

func (m *GroupAggr) GetAggrs() []*Aggregate {
	if m != nil {
		return m.Aggrs
	}
	return nil
}

func (m *GroupAggr) GetDependsOnIndexKeys() []int32 {
	if m != nil {
		return m.DependsOnIndexKeys
	}
	return nil
}

func (m *GroupAggr) GetIndexKeyNames() [][]byte {
	if m != nil {
		return m.IndexKeyNames
	}
	return nil
}

func (m *GroupAggr) GetAllowPartialAggr() bool {
	if m != nil && m.AllowPartialAggr != nil {
		return *m.AllowPartialAggr
	}
	return false
}

func (m *GroupAggr) GetOnePerPrimaryKey() bool {
	if m != nil && m.OnePerPrimaryKey != nil {
		return *m.OnePerPrimaryKey
	}
	return false
}

func init() {
	proto.RegisterType((*Error)(nil), "protobuf.Error")
	proto.RegisterType((*TsConsistency)(nil), "protobuf.TsConsistency")
	proto.RegisterType((*QueryPayload)(nil), "protobuf.QueryPayload")
	proto.RegisterType((*HeloRequest)(nil), "protobuf.HeloRequest")
	proto.RegisterType((*HeloResponse)(nil), "protobuf.HeloResponse")
	proto.RegisterType((*StatisticsRequest)(nil), "protobuf.StatisticsRequest")
	proto.RegisterType((*StatisticsResponse)(nil), "protobuf.StatisticsResponse")
	proto.RegisterType((*ScanRequest)(nil), "protobuf.ScanRequest")
	proto.RegisterType((*ScanAllRequest)(nil), "protobuf.ScanAllRequest")
	proto.RegisterType((*EndStreamRequest)(nil), "protobuf.EndStreamRequest")
	proto.RegisterType((*ResponseStream)(nil), "protobuf.ResponseStream")
	proto.RegisterType((*StreamEndResponse)(nil), "protobuf.StreamEndResponse")
	proto.RegisterType((*CountRequest)(nil), "protobuf.CountRequest")
	proto.RegisterType((*CountResponse)(nil), "protobuf.CountResponse")
	proto.RegisterType((*Span)(nil), "protobuf.Span")
	proto.RegisterType((*Range)(nil), "protobuf.Range")
	proto.RegisterType((*CompositeElementFilter)(nil), "protobuf.CompositeElementFilter")
	proto.RegisterType((*Scan)(nil), "protobuf.Scan")
	proto.RegisterType((*IndexProjection)(nil), "protobuf.IndexProjection")
	proto.RegisterType((*IndexEntry)(nil), "protobuf.IndexEntry")
	proto.RegisterType((*IndexStatistics)(nil), "protobuf.IndexStatistics")
	proto.RegisterType((*GroupKey)(nil), "protobuf.GroupKey")
	proto.RegisterType((*Aggregate)(nil), "protobuf.Aggregate")
	proto.RegisterType((*GroupAggr)(nil), "protobuf.GroupAggr")
}

func init() { proto.RegisterFile("query.proto", fileDescriptor_5c6ac9b241082464) }

var fileDescriptor_5c6ac9b241082464 = []byte{
	// 1113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x86, 0x78, 0x90, 0xc9, 0x11, 0x75, 0xf0, 0xfe, 0x39, 0xf0, 0x4f, 0xdd, 0x94, 0x20, 0xd0,
	0x96, 0x08, 0x5a, 0x23, 0x11, 0x5a, 0xa3, 0x17, 0xb9, 0x09, 0x5c, 0xb9, 0x11, 0x8c, 0xa6, 0x6a,
	0xe2, 0xab, 0xa2, 0xbd, 0x58, 0x93, 0x6b, 0x99, 0x35, 0xb5, 0x2b, 0xef, 0x92, 0x4e, 0xf4, 0x1a,
	0x7d, 0x8a, 0xbe, 0x42, 0x9f, 0xa1, 0x8f, 0xd1, 0x17, 0x29, 0x76, 0x48, 0x9a, 0x14, 0x2d, 0x20,
	0x30, 0xd0, 0x2b, 0x5b, 0x3b, 0x87, 0x9d, 0xf9, 0xe6, 0x9b, 0x6f, 0x09, 0x83, 0xeb, 0x82, 0xc9,
	0xcd, 0xe1, 0x5a, 0x8a, 0x5c, 0x10, 0x07, 0xff, 0x9c, 0x17, 0x17, 0xe1, 0x23, 0xb0, 0x67, 0x52,
	0x0a, 0x49, 0x86, 0x60, 0x33, 0xfd, 0x8f, 0xdf, 0x0b, 0x8c, 0xc8, 0x0d, 0xdf, 0xc0, 0xf0, 0x4c,
	0x1d, 0x0b, 0xae, 0x52, 0x95, 0x33, 0x1e, 0x6f, 0xb4, 0xfd, 0xe6, 0x9c, 0x0b, 0xe5, 0xf7, 0x02,
	0x33, 0x1a, 0x92, 0x11, 0xf4, 0x15, 0xbb, 0xd6, 0xbf, 0x8d, 0xc0, 0x8c, 0x2c, 0x32, 0x86, 0xbd,
	0x9b, 0xf3, 0xa2, 0x48, 0x13, 0xe5, 0x9b, 0x78, 0x30, 0x04, 0x3b, 0x96, 0xf1, 0xd1, 0x37, 0xbe,
	0x15, 0xf4, 0x22, 0x2b, 0xfc, 0xd3, 0x02, 0xef, 0x67, 0x5d, 0xc1, 0x82, 0x6e, 0x32, 0x41, 0x13,
	0x0c, 0x60, 0x52, 0xa5, 0x82, 0xe3, 0x8d, 0x43, 0x72, 0x04, 0xfb, 0x2a, 0xa7, 0x79, 0xaa, 0xf2,
	0x34, 0x56, 0x6f, 0xd9, 0x75, 0xc1, 0x54, 0xee, 0x1b, 0x41, 0x2f, 0x1a, 0x4c, 0x3f, 0x39, 0xac,
	0xeb, 0x3d, 0x7c, 0xd7, 0x75, 0x21, 0xcf, 0x01, 0x9a, 0x38, 0xdf, 0xc4, 0x80, 0x83, 0xdd, 0x01,
	0x6a, 0x2d, 0xb8, 0x62, 0xe4, 0x19, 0x0c, 0x54, 0x4c, 0x79, 0x7d, 0x87, 0x85, 0x21, 0x0f, 0x5b,
	0x21, 0x8d, 0x91, 0x3c, 0x87, 0x91, 0xf6, 0x7d, 0x95, 0x65, 0xb5, 0xbb, 0x8d, 0xee, 0xfe, 0xb6,
	0x7b, 0x63, 0x27, 0x11, 0xf4, 0x55, 0x2e, 0x19, 0x5d, 0xf9, 0xfd, 0xae, 0x67, 0x5d, 0xc1, 0x3b,
	0xb4, 0x93, 0xaf, 0xc0, 0x8b, 0x45, 0xc1, 0xf3, 0x3a, 0xf3, 0x1e, 0xfa, 0x3f, 0x6a, 0xfc, 0x8f,
	0x5b, 0x56, 0x72, 0x08, 0xc3, 0xca, 0xbb, 0x4c, 0xe2, 0x3b, 0xe8, 0xfe, 0xf8, 0x8e, 0x7b, 0xd5,
	0xe5, 0xd7, 0xe0, 0x32, 0x9e, 0x94, 0x57, 0xf9, 0x2e, 0xfa, 0x3e, 0x69, 0x7c, 0x67, 0xb5, 0xa9,
	0x49, 0xef, 0x96, 0x65, 0xcf, 0x78, 0xe2, 0xc3, 0x5d, 0xd8, 0x2b, 0x53, 0x1b, 0xc4, 0x4b, 0x96,
	0x89, 0xba, 0xf6, 0x41, 0x17, 0xc4, 0xd7, 0x8d, 0x51, 0x37, 0x5a, 0xfa, 0x56, 0x95, 0x7b, 0xdd,
	0x46, 0x5f, 0xb7, 0xac, 0xe1, 0x53, 0x18, 0xb4, 0x83, 0xbb, 0x44, 0x09, 0x3f, 0x03, 0xaf, 0xed,
	0x7f, 0xd7, 0xe1, 0x0c, 0xf6, 0xef, 0xd2, 0x64, 0x04, 0xfd, 0x84, 0x5d, 0xf0, 0xf9, 0xf7, 0xe8,
	0x64, 0x91, 0x03, 0xb0, 0xd4, 0x9a, 0x72, 0xdf, 0x08, 0x8c, 0x68, 0x30, 0x1d, 0xb5, 0x5a, 0x5d,
	0x53, 0x4e, 0xf6, 0xc1, 0x95, 0x65, 0xe0, 0x3c, 0x41, 0x4e, 0xb9, 0xe1, 0xaf, 0x40, 0x76, 0x70,
	0x29, 0x02, 0x5b, 0xb3, 0x4f, 0x61, 0xd6, 0xc1, 0xf4, 0xff, 0x4d, 0x9e, 0x39, 0x4f, 0xd8, 0x87,
	0x26, 0x82, 0x1c, 0x80, 0xc9, 0xa4, 0xac, 0x18, 0x3d, 0x6e, 0x4d, 0x42, 0x6f, 0x5d, 0xf8, 0x87,
	0x09, 0x83, 0x36, 0xef, 0xee, 0x57, 0xee, 0x04, 0x9c, 0x44, 0x5f, 0xc3, 0xe3, 0xdc, 0x37, 0x03,
	0x23, 0x72, 0xf4, 0xfa, 0x65, 0xe9, 0x2a, 0xd5, 0xec, 0x36, 0x22, 0x93, 0x78, 0x60, 0xc5, 0x82,
	0x2b, 0xdf, 0xc6, 0x55, 0xfb, 0x12, 0xfa, 0x37, 0x2c, 0xce, 0x85, 0xac, 0x28, 0xda, 0xe2, 0xd0,
	0xf6, 0xd2, 0x6f, 0xc1, 0xa0, 0xe9, 0xe9, 0x92, 0x4f, 0xc1, 0xd6, 0x0b, 0xa1, 0x7c, 0x27, 0x30,
	0x3b, 0x95, 0xc4, 0x94, 0x93, 0x29, 0x8c, 0x53, 0xdd, 0xf8, 0x5a, 0x8a, 0xdf, 0x59, 0x9c, 0xeb,
	0xa1, 0x94, 0xdc, 0xeb, 0x22, 0xb3, 0xb8, 0x75, 0xd0, 0x03, 0x94, 0x4c, 0x8f, 0x90, 0x21, 0xf1,
	0x1c, 0xdd, 0xbc, 0xb8, 0xb8, 0x50, 0xac, 0xa4, 0x95, 0x49, 0x1e, 0x80, 0x27, 0x45, 0x96, 0x9d,
	0xd3, 0xf8, 0xea, 0x2c, 0x5d, 0x95, 0xfc, 0xc1, 0xd3, 0x35, 0x95, 0x79, 0xaa, 0x73, 0xcc, 0x13,
	0xe5, 0x0f, 0x51, 0x77, 0xbe, 0x00, 0x77, 0x29, 0x45, 0xb1, 0x7e, 0xb5, 0x5c, 0x4a, 0x7f, 0x84,
	0x57, 0xff, 0xaf, 0xb9, 0xfa, 0x87, 0xda, 0x84, 0x02, 0x26, 0x64, 0xce, 0x12, 0x7f, 0x8c, 0x77,
	0x12, 0x80, 0x84, 0xe6, 0x74, 0xc6, 0xe3, 0x93, 0x55, 0xee, 0x4f, 0x82, 0x5e, 0x34, 0x0c, 0xff,
	0xea, 0xc1, 0xa8, 0xb3, 0xdd, 0xdd, 0xb9, 0xdc, 0xe2, 0x6c, 0x6c, 0xe1, 0x6c, 0x76, 0x70, 0xb6,
	0xee, 0x81, 0xb3, 0x8d, 0x38, 0x77, 0x7b, 0xee, 0xef, 0xec, 0x79, 0x0f, 0x7b, 0xde, 0xae, 0xdd,
	0xc1, 0xda, 0x09, 0x4c, 0xba, 0x3b, 0x1e, 0xfe, 0x02, 0xa3, 0x8e, 0x04, 0x3d, 0x03, 0x0f, 0xc7,
	0x35, 0xe3, 0xb9, 0x4c, 0x59, 0x29, 0xee, 0x83, 0xe9, 0x83, 0xce, 0xac, 0xb4, 0x75, 0xf3, 0x11,
	0x02, 0xbf, 0xd0, 0x4b, 0xd7, 0x15, 0x89, 0x2a, 0xa4, 0xb7, 0x3b, 0xe4, 0x9f, 0x1e, 0x78, 0x5b,
	0x12, 0x77, 0x3f, 0xd2, 0xff, 0x77, 0x58, 0xb7, 0xd7, 0xa7, 0x8f, 0x6c, 0xb8, 0x65, 0xf9, 0xde,
	0x4e, 0x96, 0x77, 0x87, 0xe3, 0xec, 0x1c, 0x8e, 0xab, 0x87, 0x13, 0xbe, 0x84, 0xe1, 0xb6, 0x30,
	0xeb, 0x97, 0x51, 0x1f, 0x60, 0x93, 0xe6, 0x47, 0x60, 0x3d, 0x02, 0x0b, 0x9b, 0x7d, 0x0a, 0xb6,
	0xa4, 0x7c, 0xc9, 0xee, 0x62, 0xf9, 0x56, 0x1f, 0x6b, 0xe8, 0xd8, 0x75, 0x41, 0xb3, 0xf2, 0x3d,
	0xf6, 0xc2, 0x6f, 0xc1, 0x2e, 0x0d, 0x03, 0x30, 0x33, 0xf1, 0x1e, 0xc3, 0x3c, 0x0d, 0xd9, 0x65,
	0xba, 0xbc, 0xc4, 0xcb, 0x3c, 0x8d, 0x44, 0xca, 0xe3, 0xac, 0x40, 0xe9, 0x44, 0x14, 0xc3, 0x13,
	0x78, 0x74, 0x2c, 0x56, 0x6b, 0xa1, 0xd2, 0x9c, 0xcd, 0x32, 0xb6, 0x62, 0x3c, 0x3f, 0x49, 0xb3,
	0x9c, 0xc9, 0x7b, 0xe6, 0x99, 0x83, 0x85, 0x40, 0xbd, 0x80, 0xbd, 0x0b, 0x8c, 0xaf, 0xa9, 0x15,
	0xb4, 0x9f, 0xab, 0x9d, 0x17, 0x75, 0x3b, 0xf9, 0x0e, 0xc6, 0x5d, 0xc1, 0xd8, 0x07, 0x17, 0x29,
	0x79, 0xca, 0x36, 0x65, 0x5e, 0x53, 0xaf, 0xc0, 0x42, 0xa6, 0x2b, 0x8a, 0x87, 0x58, 0x97, 0x13,
	0x4e, 0x01, 0x5a, 0xf4, 0x9d, 0x80, 0xc3, 0xaa, 0xa0, 0xaa, 0x0b, 0x02, 0xb0, 0x6e, 0xc7, 0x18,
	0x91, 0x17, 0xfe, 0x56, 0xdd, 0xd6, 0x12, 0xee, 0x7d, 0x70, 0xaf, 0xd8, 0x46, 0x1d, 0xdf, 0xce,
	0xcc, 0x22, 0x8f, 0x61, 0x5c, 0xf0, 0xf4, 0xba, 0x60, 0xa7, 0xb7, 0x06, 0x03, 0x0d, 0x23, 0xe8,
	0x5f, 0xb1, 0xcd, 0x8f, 0x69, 0x89, 0x83, 0x57, 0xff, 0xa6, 0x1f, 0x50, 0x87, 0xbd, 0xf0, 0x25,
	0x38, 0x28, 0x41, 0xa7, 0x6c, 0xa3, 0xaf, 0xaf, 0x0b, 0x9a, 0x27, 0x58, 0x92, 0x5d, 0xf9, 0x2f,
	0xf0, 0xb3, 0xca, 0x88, 0x6c, 0x0d, 0xb4, 0xd6, 0x52, 0x7c, 0x82, 0xbc, 0x90, 0x82, 0xab, 0xb5,
	0x8b, 0x2d, 0x69, 0xce, 0x74, 0x3f, 0x74, 0xb9, 0x94, 0x27, 0x05, 0x8f, 0xab, 0x2f, 0xa8, 0xed,
	0x84, 0x46, 0x27, 0xa1, 0xb9, 0x95, 0xd0, 0x42, 0x04, 0xda, 0xc4, 0xb7, 0x11, 0xb3, 0xbf, 0x7b,
	0xe0, 0x36, 0x22, 0xe9, 0x81, 0xc5, 0xe9, 0x8a, 0x55, 0x78, 0x7d, 0x5e, 0x49, 0x2b, 0xc2, 0x6e,
	0xe0, 0x38, 0x49, 0x47, 0x5a, 0x75, 0x5f, 0x21, 0xd8, 0xba, 0xb0, 0xf2, 0x43, 0x70, 0x4b, 0x7d,
	0x9b, 0xe2, 0x9f, 0x00, 0x49, 0xd8, 0x9a, 0xf1, 0x44, 0xfd, 0xc4, 0x11, 0x6f, 0xcc, 0x69, 0x05,
	0x66, 0x64, 0x93, 0x87, 0x30, 0x4c, 0xab, 0xa3, 0x37, 0x74, 0xc5, 0xf4, 0xa3, 0x65, 0x46, 0x1e,
	0xf1, 0x61, 0x42, 0xb3, 0x4c, 0xbc, 0x5f, 0xe8, 0x15, 0xa3, 0x19, 0xea, 0x7b, 0xb9, 0xac, 0x3e,
	0x4c, 0x04, 0x67, 0x0b, 0x26, 0x5b, 0x0c, 0xd0, 0x8f, 0x95, 0xf3, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xd6, 0xcc, 0xbd, 0x0e, 0xf5, 0x0a, 0x00, 0x00,
}
